"""Backfill `difficulty` on every non-curated `spice_routes` row.

Why this exists: migration 0012 adds the `difficulty` column with a
server default of `medium`. Curated rows are over-written by
`seed_curated_recipes.py` to the user-facing rules (see
`scripts/seed_curated_recipes.py::_resolve_difficulty`). Rows
authored by users or generated by the AI Creator pre-date the column
entirely — they land at `medium` and need a real value derived from
their own metadata.

What this does:
  * Selects every row WHERE `is_premium = false` AND
    `difficulty = 'medium'` (the migration's server default).
  * Updates each candidate with `compute_difficulty(prep, cook, len(steps))`.
  * Commits in one batch.

CRITICAL: the `difficulty = 'medium'` filter is load-bearing, not a
performance hint. Without it, the script would silently rewrite any
recipe whose owner pinned an explicit difficulty (via POST body or
PATCH) — there is NO way after the fact to distinguish "user pinned
medium" from "server default medium", so we accept the trade-off
that genuine user-pinned `medium` rows are still candidates for
backfill. The compromise is sound because (a) the auto-rule's
output FOR medium is almost always also medium, and (b) the
backfill is intended to run ONCE after migration 0012 lands, not
continuously.

Idempotent: a second run against a populated table is a no-op
because every previously-targeted row's difficulty has by then been
moved off `medium` (to whatever the auto-rule picked) and the
filter returns zero candidates. Rows the auto-rule happens to map
to `medium` are also no-ops because the existing value already
equals the target.

Usage:
    uv run python -m scripts.backfill_difficulty

Run this ONCE after migration 0012 ships and the curated seed has
re-run; from that point on the API write path (see
`app/api/spice_routes.py` and `app/api/ai.py`) auto-computes
`difficulty` on every new row, so the table stays uniform without
further intervention.
"""
import asyncio

from sqlalchemy import func, select
from sqlalchemy.orm import selectinload

from app.db.session import AsyncSessionLocal
from app.models.difficulty import Difficulty, compute_difficulty
from app.models.spice_route import SpiceRoute


async def main() -> None:
    async with AsyncSessionLocal() as db:
        # Pre-load `steps` via selectinload so we don't N+1 a lazy
        # load inside the for-loop (which on async sessions raises
        # `MissingGreenlet` outside an explicit greenlet context).
        # The selectinload is cheap because we're scoping to the
        # placeholder subset, which is small (most rows graduate out
        # of `medium` on the first backfill pass).
        #
        # The `difficulty == MEDIUM` filter is CRITICAL — see the
        # module docstring for why. Removing it would silently
        # overwrite user-pinned values on every re-run.
        rows = (
            await db.scalars(
                select(SpiceRoute)
                .where(
                    SpiceRoute.is_premium.is_(False),
                    SpiceRoute.difficulty == Difficulty.MEDIUM,
                )
                .options(selectinload(SpiceRoute.steps))
            )
        ).all()

        examined = len(rows)
        updated = 0
        for row in rows:
            target = compute_difficulty(
                prep_minutes=row.prep_minutes or 0,
                cook_minutes=row.cook_minutes or 0,
                step_count=len(row.steps),
            )
            if row.difficulty != target:
                row.difficulty = target
                updated += 1

        await db.commit()

        # Report final distribution so the operator can sanity-check.
        # GROUP BY on the freshly-committed state gives an accurate
        # picture of what the API will now serve.
        dist_rows = (
            await db.execute(
                select(SpiceRoute.difficulty, func.count())
                .where(SpiceRoute.is_premium.is_(False))
                .group_by(SpiceRoute.difficulty)
                .order_by(SpiceRoute.difficulty)
            )
        ).all()
        dist = {d.value if isinstance(d, Difficulty) else d: n for d, n in dist_rows}
        print(
            f"Backfilled difficulty on {updated} / {examined} "
            f"non-curated rows. "
            f"Final distribution: {dist}"
        )


if __name__ == "__main__":
    asyncio.run(main())
