"""v7 Myanmar regional expansion — 20 cuisines × 3 recipes (60 total).

Auto-generated by `generate_myanmar_expansion.py`.
"""

from scripts.curated_data import RecipeSpec, _img

MYANMAR_EXPANSION_RECIPES: list[RecipeSpec] = [
    {
        "title": "Shan Khauk Swe",
        "description": "Tomato-garlic rice noodles with ground pork and pickled mustard.",
        "cuisine": "shan", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("shan-khauk-swe"),
        "tags": ["noodles", "pork", "classic"],
        "ingredients": [
            {"name": "rice noodles"},
            {"name": "ground pork"},
            {"name": "tomato"},
            {"name": "garlic"},
            {"name": "pickled mustard"},
            {"name": "peanuts"}
        ],
        "steps": [
            "Fry garlic and tomato into a thick sauce.",
            "Brown pork; simmer with stock.",
            "Toss cooked noodles in sauce.",
            "Top with peanuts and mustard greens.",
            "Serve immediately."
        ],
        "translations": {
            "zh": {
                "title": "山滑水",
                "description": "番茄蒜米粉面拌猪肉酸萝卜",
            },
            "ja": {
                "title": "シィタカラエ",
                "description": "トクグヨグメングープログパーバーグ",
            },
            "ko": {
                "title": "안호엀세요",
                "description": "촌우세요치녕하세요 지호세요 촌우세요 촌우세요",
            },
            "vi": {
                "title": "Khâu Khâu Swe",
                "description": "Mì xào thịt lợn và cà chua dưa chuột muối",
            },
        },
    },
    {
        "title": "Shan Tofu Nway",
        "description": "Silky chickpea tofu in warm savory gravy over rice noodles.",
        "cuisine": "shan", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("shan-tofu-nway"),
        "tags": ["noodles", "tofu", "comfort"],
        "ingredients": [
            {"name": "chickpea flour"},
            {"name": "rice noodles"},
            {"name": "turmeric"},
            {"name": "ginger"},
            {"name": "shallot oil"},
            {"name": "chili flakes"}
        ],
        "steps": [
            "Cook chickpea batter into soft tofu.",
            "Warm noodles in shallow broth.",
            "Slice tofu over noodles.",
            "Drizzle shallot oil and chili.",
            "Serve warm."
        ],
        "translations": {
            "zh": {
                "title": "山东豆腐糊",
                "description": "细滑的鸡蛋豆腐在香浓的酱汁中,配上米粉",
            },
            "ja": {
                "title": "シャトヴァスト",
                "description": "尼帽にいるトヴァストでいるフォスン",
            },
            "ko": {
                "title": "총에경주시세요",
                "description": "장에세요 총에주시 주주세요 총에 주주세요",
            },
            "vi": {
                "title": "Đậu hũ Shan Nway",
                "description": "Đậu hũ mềm mại trong nước sốt ấm áp, phục vụ với mì gạo",
            },
        },
    },
    {
        "title": "Hinny Paw",
        "description": "Shan-style sticky rice cakes with sesame and palm sugar.",
        "cuisine": "shan", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("hinny-paw"),
        "tags": ["snack", "rice", "festival"],
        "ingredients": [
            {"name": "glutinous rice flour"},
            {"name": "palm sugar"},
            {"name": "sesame"},
            {"name": "coconut"},
            {"name": "banana leaf"}
        ],
        "steps": [
            "Mix rice flour with sugar syrup.",
            "Fold in sesame and coconut.",
            "Wrap in banana leaves.",
            "Steam 25 minutes.",
            "Cool slightly before serving."
        ],
        "translations": {
            "zh": {
                "title": "欣尼泡",
                "description": "掸族风格的糯米糕，配以芝麻和棕糖",
            },
            "ja": {
                "title": "ヒンニーパウ",
                "description": "シャン風のちまきに胡麻と棕糖",
            },
            "ko": {
                "title": "힌니파우",
                "description": "샨식 찹쌀떡에 참깨와 팜슈가",
            },
            "vi": {
                "title": "Bánh Hinny Paw Shan",
                "description": "Bánh gạo dẻo kiểu Shan với vừng và đường thốt nốt",
            },
        },
    },
    {
        "title": "Rakhine Mont Di",
        "description": "Fish-turmeric noodle soup with crisp shallots and chili oil.",
        "cuisine": "rakhine", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("rakhine-mont-di"),
        "tags": ["noodles", "fish", "classic"],
        "ingredients": [
            {"name": "rice noodles"},
            {"name": "mackerel"},
            {"name": "turmeric"},
            {"name": "shallots"},
            {"name": "chili oil"},
            {"name": "lemongrass"}
        ],
        "steps": [
            "Poach fish; flake meat.",
            "Simmer turmeric broth with lemongrass.",
            "Cook noodles separately.",
            "Assemble bowls with fish and noodles.",
            "Top with fried shallots and chili oil."
        ],
        "translations": {
            "zh": {
                "title": "若开蒙迪",
                "description": "鱼黄咖喱面汤配脆葱和辣椒油",
            },
            "ja": {
                "title": "ラカイン・モンドィ",
                "description": "魚とターメリックの麺スープ、パクチーと辣油がトッピング",
            },
            "ko": {
                "title": "라카인 몬디",
                "description": "생선-커리 라면 수프에 바삭바삭한 양파와 고추기름이 듬뿍",
            },
            "vi": {
                "title": "Món Di Rakhine",
                "description": "Súp mì cá với nghệ, hành phi giòn và dầu ớt",
            },
        },
    },
    {
        "title": "Rakhine Fish Curry",
        "description": "Coastal curry with dried chilies and ngapi shrimp paste.",
        "cuisine": "rakhine", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("rakhine-fish-curry"),
        "tags": ["curry", "fish", "coastal"],
        "ingredients": [
            {"name": "white fish"},
            {"name": "ngapi"},
            {"name": "dried chilies"},
            {"name": "garlic"},
            {"name": "turmeric"},
            {"name": "oil"}
        ],
        "steps": [
            "Marinate fish with turmeric.",
            "Fry chili-garlic paste.",
            "Simmer fish in ngapi sauce.",
            "Reduce until glossy.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "拉金鱼咖喱",
                "description": "沿海咖喱，含干红椒和酱香虾",
            },
            "ja": {
                "title": "レイサアプメイン",
                "description": "漢島温漢に当安为給温漢を用できた",
            },
            "ko": {
                "title": "짔어개개구",
                "description": "촌간가가개개구가가가가가가가가가가가가가",
            },
            "vi": {
                "title": "Cà ri cá Rakhine",
                "description": "Món cà ri bờ biển với ớt khô và nước mắm cá",
            },
        },
    },
    {
        "title": "Bamboo Shoot with Fish",
        "description": "Tender bamboo shoots braised with river fish and herbs.",
        "cuisine": "rakhine", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("bamboo-shoot-fish"),
        "tags": ["stew", "fish", "comfort"],
        "ingredients": [
            {"name": "bamboo shoots"},
            {"name": "catfish"},
            {"name": "garlic"},
            {"name": "turmeric"},
            {"name": "coriander"},
            {"name": "stock"}
        ],
        "steps": [
            "Parboil bamboo to remove bitterness.",
            "Brown fish lightly.",
            "Simmer bamboo and fish in stock.",
            "Finish with fresh coriander.",
            "Serve with steamed rice."
        ],
        "translations": {
            "zh": {
                "title": "竹笋鱼",
                "description": "嫩竹笋与河鱼和香草一起炖煮",
            },
            "ja": {
                "title": "タケノコと魚",
                "description": "やわらかい竹の子と川魚とハーブを煮込む",
            },
            "ko": {
                "title": "대나무싹과 생선",
                "description": "부드러운 대나무싹과 강어구와 허브를 조리함",
            },
            "vi": {
                "title": "Măng Tre với Cá",
                "description": "Măng tre non được hầm với cá sông và các loại thảo mộc",
            },
        },
    },
    {
        "title": "Mon Curry",
        "description": "Mild coconut curry with aromatics from lower Myanmar.",
        "cuisine": "mon", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("mon-curry"),
        "tags": ["curry", "chicken", "classic"],
        "ingredients": [
            {"name": "chicken"},
            {"name": "coconut milk"},
            {"name": "onion"},
            {"name": "garlic"},
            {"name": "ginger"},
            {"name": "Mon curry paste"}
        ],
        "steps": [
            "Bloom curry paste in oil.",
            "Brown chicken pieces.",
            "Add coconut milk; simmer 35 min.",
            "Adjust salt and palm sugar.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "王水常",
                "description": "当前水常了当前中国为常的尼常。",
            },
            "ja": {
                "title": "パャンドィンド",
                "description": "当前水常は中国为常的尼常を用だ",
            },
            "ko": {
                "title": "짔울었엘",
                "description": "안울었엘해드번세요",
            },
            "vi": {
                "title": "Món Curry",
                "description": "Phò Món Curry lónệmểmụẹtụềcụđụđợcụđụđợcụđụđợcụđụđợc",
            },
        },
    },
    {
        "title": "Mon Htamane",
        "description": "Festival sticky rice with coconut, peanuts, and sesame.",
        "cuisine": "mon", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("htamane-mon"),
        "tags": ["rice", "festival", "sweet"],
        "ingredients": [
            {"name": "glutinous rice"},
            {"name": "coconut milk"},
            {"name": "peanuts"},
            {"name": "sesame"},
            {"name": "ginger"},
            {"name": "palm sugar"}
        ],
        "steps": [
            "Soak rice overnight.",
            "Cook with coconut and sugar.",
            "Stir vigorously as it thickens.",
            "Fold in peanuts and sesame.",
            "Serve warm from the pot."
        ],
        "translations": {
            "zh": {
                "title": "級尺尺尺",
                "description": "級尺尺尺统计索强、湖尺、纳尺",
            },
            "ja": {
                "title": "フィトントン",
                "description": "フィトントンはバーグにいるだ。バーグ、インスト、レストに当前だ",
            },
            "ko": {
                "title": "총시시시",
                "description": "총시시시었세요 사원세요 총시시시 사원세요",
            },
            "vi": {
                "title": "Món Đẹt Ãn",
                "description": "Gói món Đẹt Ãn ụ ánh ỏ ánh",
            },
        },
    },
    {
        "title": "Mon Fermented Fish Dip",
        "description": "Pungent ngapi relish with chilies and lime for vegetables.",
        "cuisine": "mon", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("ngapi-dip"),
        "tags": ["dip", "fermented", "side"],
        "ingredients": [
            {"name": "ngapi"},
            {"name": "dried chilies"},
            {"name": "garlic"},
            {"name": "lime"},
            {"name": "oil"},
            {"name": "raw vegetables"}
        ],
        "steps": [
            "Pound ngapi with chilies and garlic.",
            "Fry paste until fragrant.",
            "Cool; brighten with lime.",
            "Serve with raw veg.",
            "Eat family-style."
        ],
        "translations": {
            "zh": {
                "title": "蒙古酸鱼酱",
                "description": "酸辣的酱料,配有辣椒和柠檬,适合配蔬菜",
            },
            "ja": {
                "title": "ユコクプトィサン",
                "description": "橋武でいいのトィサン, トィサンにいいだ",
            },
            "ko": {
                "title": "원어구가기울세요",
                "description": "원어구가기울세요 총세요 주세요",
            },
            "vi": {
                "title": "Cháo đề đề ảu đềp",
                "description": "Múm ảu đềp đềp ại đềp đềp đềp đềp đềp",
            },
        },
    },
    {
        "title": "Kachin Style Htamin",
        "description": "Herbed rice steamed with ginger and wild pepper leaf.",
        "cuisine": "kachin", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("kachin-rice"),
        "tags": ["rice", "aromatic", "classic"],
        "ingredients": [
            {"name": "jasmine rice"},
            {"name": "ginger"},
            {"name": "wild pepper leaf"},
            {"name": "garlic"},
            {"name": "salt"},
            {"name": "oil"}
        ],
        "steps": [
            "Rinse rice until water runs clear.",
            "Sauté ginger and garlic.",
            "Steam rice with herbs.",
            "Rest 10 minutes.",
            "Fluff and serve."
        ],
        "translations": {
            "zh": {
                "title": "加钦式米饭",
                "description": "用姜和野生胡椒叶烹饪的香草饭",
            },
            "ja": {
                "title": "カチン式ハチミ",
                "description": "生姜と野生胡椒の葉で香り高い米",
            },
            "ko": {
                "title": "카친식 햄딘",
                "description": "생강과 야생胡椒잎으로 감칠맛 나는 밥",
            },
            "vi": {
                "title": "Mì Kachin",
                "description": "Mì hấp với gừng và lá tiêu hoang dã",
            },
        },
    },
    {
        "title": "Kachin Singju",
        "description": "Tangy salad with fermented bamboo and roasted chickpea powder.",
        "cuisine": "kachin", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("kachin-singju"),
        "tags": ["salad", "vegetarian", "fresh"],
        "ingredients": [
            {"name": "fermented bamboo"},
            {"name": "cabbage"},
            {"name": "roasted chickpea powder"},
            {"name": "chili"},
            {"name": "lime"},
            {"name": "coriander"}
        ],
        "steps": [
            "Shred cabbage finely.",
            "Toss with fermented bamboo.",
            "Add chickpea powder and chili.",
            "Dress with lime.",
            "Serve immediately."
        ],
        "translations": {
            "zh": {
                "title": "克钦酸汤",
                "description": "用发酵竹笋和烤鹰嘴豆粉制成的酸辣沙拉",
            },
            "ja": {
                "title": "カチン・シンジュ",
                "description": "発酵バンブーとローストヒヨコ豆粉の酸味サラダ",
            },
            "ko": {
                "title": "카친 싱주",
                "description": "발효 竹과 로스팅 완두콩 가루의 신선한 샐러드",
            },
            "vi": {
                "title": "Gỏi Kachin Singju",
                "description": "Salad chua với măng lên men và bột đậu gà rang",
            },
        },
    },
    {
        "title": "Kachin Bamboo Shoot Soup",
        "description": "Light broth with young bamboo and smoked pork.",
        "cuisine": "kachin", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("bamboo-soup-kachin"),
        "tags": ["soup", "pork", "comfort"],
        "ingredients": [
            {"name": "young bamboo"},
            {"name": "smoked pork"},
            {"name": "ginger"},
            {"name": "garlic"},
            {"name": "stock"},
            {"name": "scallion"}
        ],
        "steps": [
            "Simmer smoked pork in stock.",
            "Add bamboo shoots.",
            "Season with ginger and garlic.",
            "Garnish with scallion.",
            "Serve hot."
        ],
        "translations": {
            "zh": {
                "title": "卡钦竹笋汤",
                "description": "清淡的汤汁中充满了新鲜的竹笋和熏猪肉",
            },
            "ja": {
                "title": "カチン・バンブーショット・スープ",
                "description": "若い竹と煙たばこ豚肉を入れた軽いスープ",
            },
            "ko": {
                "title": "카친 바무숏 수프",
                "description": "청량한 국물에 젊은 바무숏과 담근 돼지고기를 넣은 수프",
            },
            "vi": {
                "title": "Súp Cây Tre Kachin",
                "description": "Canh thanh ngọt với cây tre non và lợn hun khói",
            },
        },
    },
    {
        "title": "Kayin Sour Soup",
        "description": "Tamarind-sour soup with greens and smoked fish.",
        "cuisine": "kayin", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("kayin-sour-soup"),
        "tags": ["soup", "sour", "classic"],
        "ingredients": [
            {"name": "tamarind"},
            {"name": "smoked fish"},
            {"name": "morning glory"},
            {"name": "garlic"},
            {"name": "chili"},
            {"name": "stock"}
        ],
        "steps": [
            "Dissolve tamarind in warm stock.",
            "Simmer smoked fish.",
            "Add greens at the end.",
            "Season with garlic and chili.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "Kayin酸汤",
                "description": "酸柠檬汤,配有青菜和烟熏鱼",
            },
            "ja": {
                "title": "ケイン・サウアースープ",
                "description": "タマリンドの酸味のあるスープに青菜と煙たばした魚を混ぜたもの",
            },
            "ko": {
                "title": "케이인 소스 수프",
                "description": "타마린드의 산미가 있는 국물에青菜와 연어를 넣은 요리",
            },
            "vi": {
                "title": "Súp chua Kayin",
                "description": "Súp chua với lá xanh và cá hun khói",
            },
        },
    },
    {
        "title": "Kayin Bamboo Curry",
        "description": "Rich curry of bamboo shoots and pork belly.",
        "cuisine": "kayin", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("kayin-bamboo-curry"),
        "tags": ["curry", "pork", "comfort"],
        "ingredients": [
            {"name": "bamboo shoots"},
            {"name": "pork belly"},
            {"name": "onion"},
            {"name": "turmeric"},
            {"name": "chili paste"},
            {"name": "oil"}
        ],
        "steps": [
            "Render pork belly slowly.",
            "Add chili paste and turmeric.",
            "Simmer bamboo until tender.",
            "Reduce sauce.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "Kayin竹笋咖喱",
                "description": "竹笋和猪肚的丰富咖喱",
            },
            "ja": {
                "title": "ケイイン・バンブークリー",
                "description": "バンブーと豚の腹の豊かなカレー",
            },
            "ko": {
                "title": "케이인 바무쿠리",
                "description": "bamboo와 돼지의 배의 풍부한 카레",
            },
            "vi": {
                "title": "Kayin Gỏi Bắp Côn Trùng",
                "description": "Gỏi bắp côn trùng và lợn bụng",
            },
        },
    },
    {
        "title": "Kayin Fermented Pork",
        "description": "Sour fermented pork salad with herbs and chili.",
        "cuisine": "kayin", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("fermented-pork-kayin"),
        "tags": ["salad", "pork", "fermented"],
        "ingredients": [
            {"name": "fermented pork"},
            {"name": "shallots"},
            {"name": "chili"},
            {"name": "lime leaves"},
            {"name": "coriander"},
            {"name": "rice"}
        ],
        "steps": [
            "Slice fermented pork thin.",
            "Toss with shallots and chili.",
            "Add herbs and lime.",
            "Serve with warm rice.",
            "Eat immediately."
        ],
        "translations": {
            "zh": {
                "title": "凱因酸泡肉",
                "description": "一道酸酸甜甜的泡肉沙拉，配有香草和辣椒。",
            },
            "ja": {
                "title": "カイン・フェルメント・ポーク",
                "description": "酸味のある泡肉サラダにハーブとチリを合わせたもの。",
            },
            "ko": {
                "title": "카인 페르멘트 포크",
                "description": "산뜻한 말린고기 샐러드에 허브와 고추를 곁들인 요리.",
            },
            "vi": {
                "title": "Thịt lợn lên men Kayin",
                "description": "Món salad thịt lợn lên men chua chua ngọt ngọt, đi kèm với rau thơm và ớt.",
            },
        },
    },
    {
        "title": "Chin Baum",
        "description": "Corn rice porridge with leafy greens and smoked meat.",
        "cuisine": "chin", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("chin-baum"),
        "tags": ["rice", "corn", "comfort"],
        "ingredients": [
            {"name": "ground corn"},
            {"name": "rice"},
            {"name": "smoked meat"},
            {"name": "mustard greens"},
            {"name": "salt"},
            {"name": "water"}
        ],
        "steps": [
            "Simmer corn and rice into porridge.",
            "Shred smoked meat.",
            "Blanch greens.",
            "Assemble bowls.",
            "Serve steaming."
        ],
        "translations": {
            "zh": {
                "title": "王米嬴",
                "description": "米米美米米为米米父和米米测测求.",
            },
            "ja": {
                "title": "カイフスン",
                "description": "給水給水武武は給水給水がおだすが給水武武にきです。",
            },
            "ko": {
                "title": "주울었하세요",
                "description": "주울었하세요 주울었하세요 주울었하세요 번소었다세요.",
            },
            "vi": {
                "title": "Cá Cháo Đển",
                "description": "Cháo gày ngôt khoai mó với rau xanh và thịt xông khói.",
            },
        },
    },
    {
        "title": "Chin Smoked Meat",
        "description": "Hill-country smoked pork with chili salt.",
        "cuisine": "chin", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("chin-smoked-meat"),
        "tags": ["pork", "smoked", "classic"],
        "ingredients": [
            {"name": "pork shoulder"},
            {"name": "salt"},
            {"name": "chili flakes"},
            {"name": "ginger"},
            {"name": "garlic"},
            {"name": "smoking chips"}
        ],
        "steps": [
            "Cure pork with salt and spices.",
            "Smoke low 4 hours.",
            "Rest and slice.",
            "Serve with chili salt.",
            "Pair with rice."
        ],
        "translations": {
            "zh": {
                "title": "筸海美苹果",
                "description": "平园美苹果为给美美苹果",
            },
            "ja": {
                "title": "カドシュプムイン",
                "description": "平园美苹果にいる美苹果にいるプログル",
            },
            "ko": {
                "title": "총안세요 총안말세요",
                "description": "엀안세요 총안세요 사세요 총안말세요",
            },
            "vi": {
                "title": "ỏ᭷ỏ᭽ụẹợẽ",
                "description": "ỏ᭷ỏ᭽ụẹợẽ ễ᭽ỏ᭽ụẹợẽ",
            },
        },
    },
    {
        "title": "Chin Bamboo Stew",
        "description": "Hearty stew of bamboo, beans, and smoked beef.",
        "cuisine": "chin", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("chin-bamboo-stew"),
        "tags": ["stew", "beef", "comfort"],
        "ingredients": [
            {"name": "bamboo shoots"},
            {"name": "smoked beef"},
            {"name": "black beans"},
            {"name": "onion"},
            {"name": "garlic"},
            {"name": "stock"}
        ],
        "steps": [
            "Brown smoked beef.",
            "Add bamboo and beans.",
            "Simmer 90 minutes.",
            "Adjust seasoning.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "陈年竹笋焖",
                "description": "一道用竹笋、豆类和熏肉烹饪而成的浓郁的汤",
            },
            "ja": {
                "title": "キン・ボマー・スープ",
                "description": "竹、豆類、煙肉を使用した濃厚なスープ",
            },
            "ko": {
                "title": "친.bamboo.스튜",
                "description": "bamboo,豆류,흐어지다 소스를 사용한 진한 스템",
            },
            "vi": {
                "title": "Chin Bamboo Súp",
                "description": "Một món súp đậm đà được nấu từ tre, đậu và thịt bò hun khói",
            },
        },
    },
    {
        "title": "Kayah Pork and Rice",
        "description": "Turmeric rice cooked with pork and Kayah spices.",
        "cuisine": "kayah", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("kayah-pork-rice"),
        "tags": ["rice", "pork", "classic"],
        "ingredients": [
            {"name": "jasmine rice"},
            {"name": "pork"},
            {"name": "turmeric"},
            {"name": "garlic"},
            {"name": "Kayah spice mix"},
            {"name": "oil"}
        ],
        "steps": [
            "Marinate pork with spices.",
            "Sauté garlic and turmeric.",
            "Cook rice with pork and stock.",
            "Steam until fluffy.",
            "Rest before serving."
        ],
        "translations": {
            "zh": {
                "title": "卡亚族猪肉饭",
                "description": "用胡椒粉、香料烹饪的米饭和猪肉",
            },
            "ja": {
                "title": "キイサントフート",
                "description": "デストルトルートにフォースにフィースだ",
            },
            "ko": {
                "title": "안어안하세요",
                "description": "주어안세요 어안안하세요 안어안하세요",
            },
            "vi": {
                "title": "Cơm thịt lợn của người Kayah",
                "description": "Gạo nấu với thịt lợn và gia vị Kayah",
            },
        },
    },
    {
        "title": "Kayah Sour Leaf Soup",
        "description": "Soup of sour roselle leaves with fish and herbs.",
        "cuisine": "kayah", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("kayah-sour-leaf"),
        "tags": ["soup", "sour", "comfort"],
        "ingredients": [
            {"name": "roselle leaves"},
            {"name": "fish"},
            {"name": "tomato"},
            {"name": "garlic"},
            {"name": "chili"},
            {"name": "stock"}
        ],
        "steps": [
            "Simmer roselle leaves in stock.",
            "Add fish pieces.",
            "Finish with tomato and chili.",
            "Garnish with herbs.",
            "Serve hot."
        ],
        "translations": {
            "zh": {
                "title": "加亚酸叶汤",
                "description": "酸性红花叶的汤汁搭配鱼和香草",
            },
            "ja": {
                "title": "カヤ・サワー・リーフ・スープ",
                "description": "酸味のあるロゼッリーヌの葉を魚とハーブとともに煮込んだスープ",
            },
            "ko": {
                "title": "카야 서러리 수프",
                "description": "산뜻한 로젤리 잎과 물고기와 허브를 함께 끓인 수프",
            },
            "vi": {
                "title": "Súp lá chua Kayah",
                "description": "Súp lá chua Roselle với cá và rau thơm",
            },
        },
    },
    {
        "title": "Kayah Tomato Salad",
        "description": "Pounded tomato salad with peanuts and sesame.",
        "cuisine": "kayah", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("kayah-tomato-salad"),
        "tags": ["salad", "vegetarian", "fresh"],
        "ingredients": [
            {"name": "ripe tomatoes"},
            {"name": "peanuts"},
            {"name": "sesame"},
            {"name": "chili"},
            {"name": "lime"},
            {"name": "coriander"}
        ],
        "steps": [
            "Pound tomatoes lightly.",
            "Toast peanuts and sesame.",
            "Toss with chili and lime.",
            "Top with coriander.",
            "Serve as side."
        ],
        "translations": {
            "zh": {
                "title": "卡亚族番茄沙拉",
                "description": "用大蒜和花生碎的番茄沙拉",
            },
            "ja": {
                "title": "カヤ族トマトサラダ",
                "description": "大蒜と花生のトマトを潰して作るサラダ",
            },
            "ko": {
                "title": "카야족 토마토 샐러드",
                "description": "대파와 땅콩을 넣은 토마토를 밥쳐 만든 샐러드",
            },
            "vi": {
                "title": "Salad cà chua của người Kayah",
                "description": "Salad cà chua được làm bằng cà chua, đậu phộng và tỏi",
            },
        },
    },
    {
        "title": "Mandalay Mee Shay",
        "description": "Rice noodle soup with pork, garlic oil, and pickled greens.",
        "cuisine": "mandalay", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("mee-shay"),
        "tags": ["noodles", "pork", "classic"],
        "ingredients": [
            {"name": "rice noodles"},
            {"name": "pork"},
            {"name": "garlic oil"},
            {"name": "pickled mustard"},
            {"name": "soy"},
            {"name": "stock"}
        ],
        "steps": [
            "Simmer pork in spiced stock.",
            "Cook noodles.",
            "Assemble bowls.",
            "Top with garlic oil and pickles.",
            "Serve immediately."
        ],
        "translations": {
            "zh": {
                "title": "曼德勒面汤",
                "description": "米粉汤搭配猪肉、蒜油和腌制青菜",
            },
            "ja": {
                "title": "マンダレー・ミーシェイ",
                "description": "豚肉とガーリックオイル、ピクルスグリーンが入ったライスヌードルスープ",
            },
            "ko": {
                "title": "만달레이 mee shay",
                "description": "돼지고기, 마늘기름, 절인 채소가 들어간 라이스 누들 수프",
            },
            "vi": {
                "title": "Mee Shay Mandalay",
                "description": "Súp mì gạo với thịt lợn, dầu tỏi và rau muối",
            },
        },
    },
    {
        "title": "Mandalay Tea Leaf Salad",
        "description": "Royal-city laphet thoke with crunchy mix-ins.",
        "cuisine": "mandalay", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("mandalay-tea-leaf"),
        "tags": ["salad", "fermented", "classic"],
        "ingredients": [
            {"name": "fermented tea leaves"},
            {"name": "fried garlic"},
            {"name": "peanuts"},
            {"name": "sesame"},
            {"name": "tomato"},
            {"name": "cabbage"}
        ],
        "steps": [
            "Mix tea leaves with aromatics.",
            "Toast peanuts and sesame.",
            "Toss with shredded cabbage.",
            "Add tomato and fried garlic.",
            "Serve family-style."
        ],
        "translations": {
            "zh": {
                "title": "曼德勒茶叶沙拉",
                "description": "曼德勒皇城的拉菲特托克，伴有多种脆口的混合物",
            },
            "ja": {
                "title": "マチメインスイェア",
                "description": "メンムイェアはメンムイェアにいなただ",
            },
            "ko": {
                "title": "안호백안구주세요",
                "description": "안호세요백세요 백안백 접세요",
            },
            "vi": {
                "title": "Salad lá trà Mandalay",
                "description": "Salad lá trà của thành phố hoàng gia Mandalay với hỗn hợp crunchy",
            },
        },
    },
    {
        "title": "Mandalay Beef Curry",
        "description": "Slow-braised beef with star anise and onion.",
        "cuisine": "mandalay", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("mandalay-beef-curry"),
        "tags": ["curry", "beef", "comfort"],
        "ingredients": [
            {"name": "beef chuck"},
            {"name": "onion"},
            {"name": "star anise"},
            {"name": "turmeric"},
            {"name": "garlic"},
            {"name": "oil"}
        ],
        "steps": [
            "Brown beef in batches.",
            "Caramelize onions.",
            "Braise with spices 2 hours.",
            "Reduce gravy.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "王尼置彗湼張",
                "description": "正得住尼不得置和纳汏",
            },
            "ja": {
                "title": "ビイトバープック",
                "description": "正得住尼に得したディショナにがいによう",
            },
            "ko": {
                "title": "총백엀다호요세요",
                "description": "총백엀다호요세요 안녕는 총엀세요",
            },
            "vi": {
                "title": "ỉ᯾ởộẹỏụểợếụ",
                "description": "ỉ᯾ởộẹỏụểợếụ ỉ᯾ởộẹỏụểợếụ",
            },
        },
    },
    {
        "title": "Yangon Mohinga",
        "description": "Street-style fish noodle soup with crisp fritters.",
        "cuisine": "yangon", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("yangon-mohinga"),
        "tags": ["noodles", "fish", "street food"],
        "ingredients": [
            {"name": "rice noodles"},
            {"name": "catfish"},
            {"name": "rice flour"},
            {"name": "turmeric"},
            {"name": "banana stem"},
            {"name": "crispy fritters"}
        ],
        "steps": [
            "Make fish broth with turmeric.",
            "Whisk rice flour slurry to thicken.",
            "Cook noodles.",
            "Assemble with banana stem.",
            "Top with fritters and lime."
        ],
        "translations": {
            "zh": {
                "title": "王尼尽美",
                "description": "平纸美美走尽美和累美尽美",
            },
            "ja": {
                "title": "バーコンタエス",
                "description": "宮紦にからいの美美走でいる美美。当前にいの累美尽美でいる",
            },
            "ko": {
                "title": "개에구가가기가구",
                "description": "고고구가가기가가가가구가가가가가",
            },
            "vi": {
                "title": "Mó Hóngiña Yangon",
                "description": "Món hóngiña đường phố với fritters giòn",
            },
        },
    },
    {
        "title": "Yangon Samosa Thoke",
        "description": "Chopped samosa salad with chickpea curry and herbs.",
        "cuisine": "yangon", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("samosa-thoke"),
        "tags": ["salad", "street food", "snack"],
        "ingredients": [
            {"name": "samosa"},
            {"name": "chickpea curry"},
            {"name": "cabbage"},
            {"name": "mint"},
            {"name": "lime"},
            {"name": "chili"}
        ],
        "steps": [
            "Fry samosas crisp.",
            "Chop and toss with cabbage.",
            "Spoon warm chickpea curry.",
            "Finish with mint and lime.",
            "Serve immediately."
        ],
        "translations": {
            "zh": {
                "title": "仰光三角饺子拌饭",
                "description": "切碎的三角饺子拌饭,配有鸡豆咖喱和香草。",
            },
            "ja": {
                "title": "エメバイサタンディスト",
                "description": "デシェアタンディストにきるためバームインディスト。",
            },
            "ko": {
                "title": "안었 상신시촍세요 총소시촍세요",
                "description": "상신시촍세요 총소시촍세요 주가주 총소시촍세요 주가주 총소시촍세요 총소시촍세요。",
            },
            "vi": {
                "title": "Samosa Yangon",
                "description": "Salad samosa xay với cà ri đậu gà và rau thơm.",
            },
        },
    },
    {
        "title": "Tea Shop Eggs",
        "description": "Soft-boiled eggs with soy-pepper dip from corner tea stalls.",
        "cuisine": "yangon", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("tea-shop-eggs"),
        "tags": ["eggs", "breakfast", "street food"],
        "ingredients": [
            {"name": "eggs"},
            {"name": "soy sauce"},
            {"name": "pepper"},
            {"name": "chili oil"},
            {"name": "scallion"},
            {"name": "toast"}
        ],
        "steps": [
            "Soft-boil eggs 6 minutes.",
            "Make soy-pepper dip.",
            "Peel and halve eggs.",
            "Drizzle chili oil.",
            "Serve with toast."
        ],
        "translations": {
            "zh": {
                "title": "茶铺卤蛋",
                "description": "仰光街角茶摊的经典小食：半熟溏心蛋，配酱油胡椒蘸汁与辣椒油。",
            },
            "ja": {
                "title": "ミャンマーチャーショップ風たまご",
                "description": "ヤンゴンの路地の茶屋の定番。半熟卵に醤油と胡椒のたれ、ラー油を添えて。",
            },
            "ko": {
                "title": "미얀마 찻집 반숙 달걀",
                "description": "양곤 거리 찻집의 아침 메뉴. 반숙 달걀에 간장·후추 소스와 고추기름을 곁들입니다.",
            },
            "vi": {
                "title": "Trứng luộc kiểu quán trà",
                "description": "Trứng luộc lòng đào với nước chấm xì dầu tiêu — món quen ở các quán trà góc phố Yangon.",
            },
        },
    },
    {
        "title": "Delta Fish Curry",
        "description": "Irrawaddy Delta fish curry with tamarind and herbs.",
        "cuisine": "ayeyarwady", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("delta-fish-curry"),
        "tags": ["curry", "fish", "classic"],
        "ingredients": [
            {"name": "river fish"},
            {"name": "tamarind"},
            {"name": "turmeric"},
            {"name": "garlic"},
            {"name": "cilantro"},
            {"name": "oil"}
        ],
        "steps": [
            "Marinate fish with turmeric.",
            "Fry aromatics.",
            "Simmer in tamarind sauce.",
            "Garnish with cilantro.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "三角洲鱼咖喱",
                "description": "伊洛瓦底江三角洲风味的酸角香草鱼咖喱。",
            },
            "ja": {
                "title": "デルタ魚のカレー",
                "description": "タマリンドとハーブで香るイラワジー川デルタの魚カレー。",
            },
            "ko": {
                "title": "델타 생선 카레",
                "description": "타마린드와 허브가 어우러진 이라와디 강 델타 생선 카레.",
            },
            "vi": {
                "title": "Cà ri cá đồng bằng",
                "description": "Cà ri cá vùng đồng bằng Irrawaddy với me và thảo mộc.",
            },
        },
    },
    {
        "title": "River Prawn Soup",
        "description": "Sweet prawn broth with morning glory and lime.",
        "cuisine": "ayeyarwady", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("river-prawn-soup"),
        "tags": ["soup", "seafood", "comfort"],
        "ingredients": [
            {"name": "river prawns"},
            {"name": "morning glory"},
            {"name": "lime"},
            {"name": "garlic"},
            {"name": "ginger"},
            {"name": "stock"}
        ],
        "steps": [
            "Shell prawns; reserve heads for stock.",
            "Simmer broth with aromatics.",
            "Poach prawns briefly.",
            "Add greens at end.",
            "Serve with lime."
        ],
        "translations": {
            "zh": {
                "title": "漸温纳湖水",
                "description": "漸温纳水也一月和美尼一中",
            },
            "ja": {
                "title": "アヨバンバーサント",
                "description": "アヨバンバーサントにいるバートにきだ",
            },
            "ko": {
                "title": "골가구가구가가가구가",
                "description": "골가구가가가가가구가가가가가",
            },
            "vi": {
                "title": "ỉộặểụệềứị",
                "description": "ỉộặểụệềứịợếụẽịị",
            },
        },
    },
    {
        "title": "Ayeyarwady Tamarind Fish",
        "description": "Whole fish glazed with delta tamarind and palm sugar.",
        "cuisine": "ayeyarwady", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("tamarind-fish"),
        "tags": ["fish", "sweet-sour", "classic"],
        "ingredients": [
            {"name": "whole fish"},
            {"name": "tamarind paste"},
            {"name": "palm sugar"},
            {"name": "garlic"},
            {"name": "chili"},
            {"name": "oil"}
        ],
        "steps": [
            "Fry fish until golden.",
            "Reduce tamarind and sugar glaze.",
            "Coat fish in glaze.",
            "Garnish with chili.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "阿耶亚拉威淡奶酪鱼",
                "description": "用阿耶亚拉威河delta地区的淡奶酪和椰糖浇酱的整条鱼",
            },
            "ja": {
                "title": "アヤラワティマリンダ魚",
                "description": "デルタのタマリンダと椰糖でグレードした魚",
            },
            "ko": {
                "title": "아야라와티 마린다 어",
                "description": "델타의 마린다와 코코넛 설탕으로 그레이드한 어",
            },
            "vi": {
                "title": "Cá tôm chua ngọt sông Ayeyarwady",
                "description": "Cá nguyên con được ướp với tamarind và đường mật",
            },
        },
    },
    {
        "title": "Southern Myanmar Sour Curry",
        "description": "Peninsula sour curry with green mango and seafood.",
        "cuisine": "tanintharyi", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("southern-sour-curry"),
        "tags": ["curry", "seafood", "sour"],
        "ingredients": [
            {"name": "fish or prawns"},
            {"name": "green mango"},
            {"name": "turmeric"},
            {"name": "chili"},
            {"name": "ngapi"},
            {"name": "oil"}
        ],
        "steps": [
            "Make sour base with green mango.",
            "Add seafood and simmer.",
            "Season with ngapi.",
            "Finish with fresh chili.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "南缅甸酸辣咖喱",
                "description": "半岛酸辣咖喱配绿芒果和海鲜",
            },
            "ja": {
                "title": "ミャンマー南部酸辛カレー",
                "description": "グリーンマンゴーと海鮮のペニンシュラ酸辛カレー",
            },
            "ko": {
                "title": "미얀마 남부 산미 간장 카레",
                "description": "그린 망고와 해산물의 반도 산미 간장 카레",
            },
            "vi": {
                "title": "Cà ri chua cay miền Nam Miến Điện",
                "description": "Cà ri chua cay bán đảo với xoài xanh và hải sản",
            },
        },
    },
    {
        "title": "Coastal Crab Curry",
        "description": "Spiced crab curry from the Tanintharyi coast.",
        "cuisine": "tanintharyi", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("coastal-crab-curry"),
        "tags": ["curry", "crab", "coastal"],
        "ingredients": [
            {"name": "mud crab"},
            {"name": "turmeric"},
            {"name": "garlic"},
            {"name": "dried chilies"},
            {"name": "coconut milk"},
            {"name": "lemongrass"}
        ],
        "steps": [
            "Clean and crack crab.",
            "Fry chili-turmeric paste.",
            "Simmer crab in coconut milk.",
            "Reduce until thick.",
            "Serve immediately."
        ],
        "translations": {
            "zh": {
                "title": "尾尾美浦浦",
                "description": "平浦浦美浦浦、一个尾尾浦浦的游涁彩彩水浦浦",
            },
            "ja": {
                "title": "カシュールドーコーー",
                "description": "後浦浦、一个カシュールドーコーーにいだ",
            },
            "ko": {
                "title": "구기가과구과",
                "description": "平가과과가가가가가가가가가가가가가가",
            },
            "vi": {
                "title": "Đảđạảỏụẹợỏ",
                "description": "Đảđạảỏụẹợỏ、一ảấạảỏụẹợỏ、ợếủềụẹợỏ",
            },
        },
    },
    {
        "title": "Dawei Noodles",
        "description": "Southern coastal noodles with fish cake and peanut.",
        "cuisine": "tanintharyi", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("dawei-noodles"),
        "tags": ["noodles", "fish", "street food"],
        "ingredients": [
            {"name": "rice noodles"},
            {"name": "fish cake"},
            {"name": "peanuts"},
            {"name": "garlic oil"},
            {"name": "lime"},
            {"name": "stock"}
        ],
        "steps": [
            "Simmer fish cake in broth.",
            "Cook noodles.",
            "Toss with garlic oil.",
            "Top with peanuts and lime.",
            "Serve hot."
        ],
        "translations": {
            "zh": {
                "title": "王江约尼",
                "description": "测纷浏览的测纷。约尼纷和米尼。",
            },
            "ja": {
                "title": "アイスインコン",
                "description": "测纷浏览的测纷。约尼纷和米尼。",
            },
            "ko": {
                "title": "구고가과구",
                "description": "测纷浏览的测纷。约尼纷和米尼。",
            },
            "vi": {
                "title": "ỉ᭽ụởẹợẽẹợ",
                "description": "测纷浏览的测纷。约尼纷和米尼。",
            },
        },
    },
    {
        "title": "Inle Htamin Jin",
        "description": "Inle fermented rice cake with tomato and sesame.",
        "cuisine": "intha", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("intha-htamin-jin"),
        "tags": ["rice", "fermented", "classic"],
        "ingredients": [
            {"name": "cooked rice"},
            {"name": "tomato"},
            {"name": "sesame"},
            {"name": "peanuts"},
            {"name": "garlic"},
            {"name": "chili"}
        ],
        "steps": [
            "Ferment rice lightly overnight.",
            "Pan-fry cakes until crisp.",
            "Top with tomato-chili relish.",
            "Garnish with sesame.",
            "Serve warm."
        ],
        "translations": {
            "zh": {
                "title": "张米尽字强",
                "description": "张米筸尽强中尽筸尽一尽强一尽",
            },
            "ja": {
                "title": "アライトフィターヒトル",
                "description": "アライトフィターヒトルに下了パトィターヒトル",
            },
            "ko": {
                "title": "짔타백타번세요",
                "description": "짔타백타번세요 총고세요 총고세요 직세요",
            },
            "vi": {
                "title": "Bánh ần đển đển",
                "description": "Bánh ần ển đển ỉ đển đển đển",
            },
        },
    },
    {
        "title": "Inle Tomato Salad",
        "description": "Lake-region tomato salad with roasted peanuts.",
        "cuisine": "intha", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("intha-tomato-salad"),
        "tags": ["salad", "vegetarian", "fresh"],
        "ingredients": [
            {"name": "ripe tomatoes"},
            {"name": "peanuts"},
            {"name": "sesame"},
            {"name": "lime"},
            {"name": "chili"},
            {"name": "shallots"}
        ],
        "steps": [
            "Slice tomatoes thick.",
            "Toast peanuts.",
            "Dress with lime and chili.",
            "Garnish with shallots.",
            "Serve chilled."
        ],
        "translations": {
            "zh": {
                "title": "因陀罗番茄沙拉",
                "description": "来自因陀罗湖区的番茄沙拉，配有烤花生",
            },
            "ja": {
                "title": "インレ・トマト・サラダ",
                "description": "インレ湖地方のトマトサラダに、焼いたピーナッツを合わせたもの",
            },
            "ko": {
                "title": "인레 토마토 샐러드",
                "description": "인레 지역의 토마토 샐러드에 볶은 땅콩을 더한 것",
            },
            "vi": {
                "title": "Salad cà chua Inle",
                "description": "Salad cà chua vùng hồ Inle với hạt điều rang",
            },
        },
    },
    {
        "title": "Inle Fish Curry",
        "description": "Mild tomato fish curry from floating gardens.",
        "cuisine": "intha", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("intha-fish-curry"),
        "tags": ["curry", "fish", "comfort"],
        "ingredients": [
            {"name": "Inle carp"},
            {"name": "tomato"},
            {"name": "turmeric"},
            {"name": "garlic"},
            {"name": "onion"},
            {"name": "oil"}
        ],
        "steps": [
            "Fry fish lightly.",
            "Cook tomato-onion base.",
            "Simmer fish in sauce.",
            "Rest flavors 5 minutes.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "經安美湿橋漸温",
                "description": "武一统计美湿橋漸温。很事布江橋漸温。",
            },
            "ja": {
                "title": "アトフィールフィル",
                "description": "本三のトィフィルにいない。很事布のフィルにいない。",
            },
            "ko": {
                "title": "구가기개국가가가국가",
                "description": "구가기개가가가국가가가가국가가가가국가가가가",
            },
            "vi": {
                "title": "Đễnhỉ Đố ảu ỏ đểu",
                "description": "Đễnhỉ Đố ảu ỏ đểu đểu ỏ đểu đểu đểu đểu đểu đểu",
            },
        },
    },
    {
        "title": "Naga Smoked Pork",
        "description": "Smoky hill pork with king chili and herbs.",
        "cuisine": "naga", "language": "en", "spice_level": 3,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("naga-smoked-pork"),
        "tags": ["pork", "smoked", "spicy"],
        "ingredients": [
            {"name": "pork belly"},
            {"name": "king chili"},
            {"name": "ginger"},
            {"name": "garlic"},
            {"name": "salt"},
            {"name": "smoking wood"}
        ],
        "steps": [
            "Salt pork overnight.",
            "Smoke over low heat.",
            "Char chili and pound.",
            "Toss pork with chili paste.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "南加烟熏猪肉",
                "description": "南加烟熏猪肉,带有国王辣椒和香草的烟熏山猪肉。",
            },
            "ja": {
                "title": "ナガ・スモーク・ポーク",
                "description": "ナガ・スモーク・ポーク、国王チリとハーブが入った煙焼きの山の豚肉です。",
            },
            "ko": {
                "title": "나가 스모크 포크",
                "description": "나가 스모크 포크는 국왕 치리와 허브가 들어간 담근 산의 돼지肉입니다.",
            },
            "vi": {
                "title": "Naga Sương Mù Lợn",
                "description": "Naga Sương Mù Lợn với quốc vương ớt và rau thơm",
            },
        },
    },
    {
        "title": "Naga Bamboo Shoot Stew",
        "description": "Fiery bamboo stew with smoked meat and herbs.",
        "cuisine": "naga", "language": "en", "spice_level": 3,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("naga-bamboo"),
        "tags": ["stew", "bamboo", "spicy"],
        "ingredients": [
            {"name": "bamboo shoots"},
            {"name": "smoked meat"},
            {"name": "king chili"},
            {"name": "ginger"},
            {"name": "garlic"},
            {"name": "stock"}
        ],
        "steps": [
            "Parboil bamboo.",
            "Simmer smoked meat in stock.",
            "Add chili and bamboo.",
            "Cook until tender.",
            "Serve hot."
        ],
        "translations": {
            "zh": {
                "title": "红红機機橋橋橋橋橋",
                "description": "红红機機橋橋橋橋橋橋橋橋橋橋橋",
            },
            "ja": {
                "title": "パェアバトコンショナーター",
                "description": "パェアバトコンショナーターできういだ",
            },
            "ko": {
                "title": "구가기가구가가가가가가가가가",
                "description": "구가기가가가가가가가가가가가가가",
            },
            "vi": {
                "title": "ỉẽợẽụẽợẽụẽợẽụẽ",
                "description": "ỉẽợẽụẽợẽụẽợẽụẽợẽụẽ",
            },
        },
    },
    {
        "title": "Naga King Chili Chutney",
        "description": "Incendiary chutney of king chilies and fermented soy.",
        "cuisine": "naga", "language": "en", "spice_level": 3,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("naga-chili-chutney"),
        "tags": ["condiment", "spicy", "fermented"],
        "ingredients": [
            {"name": "king chilies"},
            {"name": "fermented soy"},
            {"name": "garlic"},
            {"name": "salt"},
            {"name": "lime"},
            {"name": "oil"}
        ],
        "steps": [
            "Roast chilies.",
            "Pound with fermented soy.",
            "Fry briefly in oil.",
            "Cool and jar.",
            "Use sparingly."
        ],
        "translations": {
            "zh": {
                "title": "麻婆王椒酱",
                "description": "麻婆王椒酱是由王椒和发酵豆制成的一种烈性酱",
            },
            "ja": {
                "title": "アヒタパディター",
                "description": "アヒタパディターはアヒタパ、パッツショナにコンターを代下だ",
            },
            "ko": {
                "title": "촌번안장었세요",
                "description": "촌번안장었세요하세요 안장었세요 촌번안장었세요를세요",
            },
            "vi": {
                "title": "Ché Chùt Nàga Vóng",
                "description": "Ché chùt nàga vóng làm làm vàng vóng",
            },
        },
    },
    {
        "title": "Pa'O Htamin Jin",
        "description": "Pa'O fermented rice cakes with garlic and chili.",
        "cuisine": "pa_o", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("pao-htamin-jin"),
        "tags": ["rice", "fermented", "classic"],
        "ingredients": [
            {"name": "cooked rice"},
            {"name": "garlic"},
            {"name": "chili"},
            {"name": "sesame"},
            {"name": "oil"},
            {"name": "salt"}
        ],
        "steps": [
            "Shape rice into patties.",
            "Pan-fry until crisp.",
            "Top with fried garlic.",
            "Add chili oil.",
            "Serve warm."
        ],
        "translations": {
            "zh": {
                "title": "白族发酵米饼",
                "description": "白族发酵米饼配有蒜和辣椒",
            },
            "ja": {
                "title": "パオ・フトミン・ジン",
                "description": "パオの発酵米餅にガーリックとチリを合わせたもの",
            },
            "ko": {
                "title": "파오 훠민진",
                "description": "파오 발효 쌀과자에 마늘과 고추를 곁들인 요리",
            },
            "vi": {
                "title": "Bánh gạo lên men Pa'O",
                "description": "Bánh gạo lên men Pa'O với tỏi và ớt",
            },
        },
    },
    {
        "title": "Pa'O Shan Tofu",
        "description": "Chickpea tofu salad with herbs from Pa'O hills.",
        "cuisine": "pa_o", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("pao-shan-tofu"),
        "tags": ["salad", "tofu", "vegetarian"],
        "ingredients": [
            {"name": "chickpea tofu"},
            {"name": "coriander"},
            {"name": "lime"},
            {"name": "chili"},
            {"name": "shallot oil"},
            {"name": "peanuts"}
        ],
        "steps": [
            "Slice tofu thick.",
            "Dress with lime and chili.",
            "Top with herbs and peanuts.",
            "Drizzle shallot oil.",
            "Serve fresh."
        ],
        "translations": {
            "zh": {
                "title": "帕奥山豆腐",
                "description": "帕奥山地区的鸡豆豆腐沙拉",
            },
            "ja": {
                "title": "バエサイン・トン",
                "description": "バエサイン・トンコーターにいるバーターストイン",
            },
            "ko": {
                "title": "촌식안퉈",
                "description": "촌식안퉈백 주세요",
            },
            "vi": {
                "title": "Tofu Pa'O Shan",
                "description": "Salad đậu gà từ vùng núi Pa'O",
            },
        },
    },
    {
        "title": "Pa'O Sour Mustard",
        "description": "Pickled mustard greens stir-fried with pork.",
        "cuisine": "pa_o", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("pao-sour-mustard"),
        "tags": ["stir-fry", "pork", "pickled"],
        "ingredients": [
            {"name": "pickled mustard"},
            {"name": "pork"},
            {"name": "garlic"},
            {"name": "chili"},
            {"name": "oil"},
            {"name": "soy"}
        ],
        "steps": [
            "Rinse pickled mustard.",
            "Stir-fry pork and garlic.",
            "Add mustard and chili.",
            "Toss over high heat.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "傣族酸辣芽菜",
                "description": "傣族酸辣芽菜炒猪肉",
            },
            "ja": {
                "title": "パオ サワー マスタード",
                "description": "ピクルード マスタードグリーンを豚肉と炒める料理",
            },
            "ko": {
                "title": "파오 소어 마스타드",
                "description": "파오 소어 마스타드에 돼지고기와 볶다",
            },
            "vi": {
                "title": "Pa'O Sốt Mù Tạt",
                "description": "Cải mù tạt ngâm chua ngọt xào thịt lợn",
            },
        },
    },
    {
        "title": "Danu Fermented Tea Rice",
        "description": "Danu celebratory rice mixed with laphet and nuts.",
        "cuisine": "danu", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("danu-fermented-tea"),
        "tags": ["rice", "fermented", "festival"],
        "ingredients": [
            {"name": "steamed rice"},
            {"name": "fermented tea leaves"},
            {"name": "peanuts"},
            {"name": "sesame"},
            {"name": "fried garlic"},
            {"name": "oil"}
        ],
        "steps": [
            "Cool rice slightly.",
            "Fold in tea leaves and nuts.",
            "Season with salt.",
            "Garnish with fried garlic.",
            "Serve at room temperature."
        ],
        "translations": {
            "zh": {
                "title": "王美気気美飯",
                "description": "王美気気美飯为一个有约得的飯飯。",
            },
            "ja": {
                "title": "トンディントンディント",
                "description": "トンディントンディントは得的にきる飯飯できる",
            },
            "ko": {
                "title": "총을하세요로세요",
                "description": "총을하세요로세요대댔를 총을하세요로세요대댔를",
            },
            "vi": {
                "title": "Thái đáu Đáu Đáu",
                "description": "Thái đáu Đáu Đáu làm đày đáu đáu.",
            },
        },
    },
    {
        "title": "Danu Pork Curry",
        "description": "Mountain pork curry with turmeric and ginger.",
        "cuisine": "danu", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("danu-pork-curry"),
        "tags": ["curry", "pork", "comfort"],
        "ingredients": [
            {"name": "pork"},
            {"name": "turmeric"},
            {"name": "ginger"},
            {"name": "garlic"},
            {"name": "chili paste"},
            {"name": "oil"}
        ],
        "steps": [
            "Brown pork.",
            "Add chili paste and turmeric.",
            "Simmer until tender.",
            "Reduce sauce.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "丹努猪肉咖喱",
                "description": "山地猪肉咖喱,用黄姜和姜调味",
            },
            "ja": {
                "title": "トイゴンフーチティ",
                "description": "尿尿状水尿ティサンを用に影氿できい",
            },
            "ko": {
                "title": "안어호었백회세요",
                "description": "안어호었백회세요시다 상세요",
            },
            "vi": {
                "title": "Cà ri lợn Danu",
                "description": "Cà ri lợn núi với nghệ và gừng",
            },
        },
    },
    {
        "title": "Danu Rice Wine Chicken",
        "description": "Chicken braised with homemade rice wine aromatics.",
        "cuisine": "danu", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("danu-chicken"),
        "tags": ["chicken", "braised", "classic"],
        "ingredients": [
            {"name": "chicken"},
            {"name": "rice wine"},
            {"name": "ginger"},
            {"name": "garlic"},
            {"name": "soy"},
            {"name": "scallion"}
        ],
        "steps": [
            "Marinate chicken in wine.",
            "Braise with ginger 40 min.",
            "Reduce liquid.",
            "Garnish with scallion.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "统计美金王美",
                "description": "美王綂子之常求不正得綂子求不正得綂子求不正得綂子求不正得綂子求不正得綂子求不正得綂子求不正得",
            },
            "ja": {
                "title": "トイベントインスタイントインスタイン",
                "description": "トイベントインスタイントインスタイントインスタイントインスタイン",
            },
            "ko": {
                "title": "가좋세요안세요었세요",
                "description": "안세요 었세요 총고을 주세요었세요 안세요 총고을 주세요",
            },
            "vi": {
                "title": "ỉ ᬊầ ᬊầ ᬊầ ᬊầ ᬊầ ᬊầ ᬊầ",
                "description": "ỉ ᬊầ ᬊầ ᬊầ ᬊầ ᬊầ ᬊầ ᬊầ ᬊầ ᬊầ ᬊầ",
            },
        },
    },
    {
        "title": "Wa Grilled Meat",
        "description": "Char-grilled marinated meat with wild herbs.",
        "cuisine": "wa", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("wa-grilled-meat"),
        "tags": ["grill", "beef", "classic"],
        "ingredients": [
            {"name": "beef"},
            {"name": "wild herbs"},
            {"name": "chili"},
            {"name": "garlic"},
            {"name": "salt"},
            {"name": "lime"}
        ],
        "steps": [
            "Marinate beef with herbs.",
            "Grill over high heat.",
            "Rest and slice.",
            "Serve with lime and chili.",
            "Eat with sticky rice."
        ],
        "translations": {
            "zh": {
                "title": "瓦烤肉",
                "description": "用野生香草调味的烤肉",
            },
            "ja": {
                "title": "エィコンバー",
                "description": "給溬の張フォースが張だ",
            },
            "ko": {
                "title": "주안가구",
                "description": "안호가가구가가가가구",
            },
            "vi": {
                "title": "Thịt nướng Wa",
                "description": "Thịt nướng được ướp với các loại rau hoang dại",
            },
        },
    },
    {
        "title": "Wa Chili Paste",
        "description": "Bold chili paste with fermented beans and herbs.",
        "cuisine": "wa", "language": "en", "spice_level": 3,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("wa-chili-paste"),
        "tags": ["condiment", "spicy", "fermented"],
        "ingredients": [
            {"name": "dried chilies"},
            {"name": "fermented beans"},
            {"name": "garlic"},
            {"name": "salt"},
            {"name": "herbs"},
            {"name": "oil"}
        ],
        "steps": [
            "Toast chilies.",
            "Pound with beans and garlic.",
            "Fry in oil.",
            "Cool before serving.",
            "Use as dip."
        ],
        "translations": {
            "zh": {
                "title": "瓦椒酱",
                "description": "一种带有发酵豆子和香草的浓烈椒酱",
            },
            "ja": {
                "title": "エィディン",
                "description": "当前不正役ディディは後後に不正役。",
            },
            "ko": {
                "title": "이백호마",
                "description": "안녕호마는번다번다번다세요",
            },
            "vi": {
                "title": "Cháo đềi",
                "description": "Một loại cháo đềi nùng áp ạu ễa đổi",
            },
        },
    },
    {
        "title": "Wa Sticky Rice",
        "description": "Steamed sticky rice served with grilled meats and herbs.",
        "cuisine": "wa", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("wa-rice"),
        "tags": ["rice", "side", "classic"],
        "ingredients": [
            {"name": "glutinous rice"},
            {"name": "salt"},
            {"name": "banana leaf"},
            {"name": "herbs"}
        ],
        "steps": [
            "Soak rice 4 hours.",
            "Steam in banana leaf.",
            "Fluff with salt.",
            "Serve with meats.",
            "Eat with hands."
        ],
        "translations": {
            "zh": {
                "title": "瓦斯蒂基饭",
                "description": "用蒸汽烹饪的黏稠饭伴有烤肉和香草",
            },
            "ja": {
                "title": "エコティコイン",
                "description": "影海尽常王に中尽常に張だ",
            },
            "ko": {
                "title": "지어세요 주세요",
                "description": "주세요 었세요 주세요 총고세요 주세요 주세요 주세요",
            },
            "vi": {
                "title": "Gạo dẻo Wa",
                "description": "Gạo dẻo được hấp chín với thịt nướng và rau thơm",
            },
        },
    },
    {
        "title": "Dry Zone Peanut Curry",
        "description": "Central Myanmar peanut curry with chicken.",
        "cuisine": "magway", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("peanut-curry"),
        "tags": ["curry", "chicken", "peanut"],
        "ingredients": [
            {"name": "chicken"},
            {"name": "peanuts"},
            {"name": "turmeric"},
            {"name": "onion"},
            {"name": "garlic"},
            {"name": "oil"}
        ],
        "steps": [
            "Grind peanuts to paste.",
            "Brown chicken.",
            "Simmer in peanut sauce.",
            "Reduce until thick.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "篇中纳尽尽游子",
                "description": "中国为尽尽纳尽游子，为当前中国为尽尽纳尽游子。",
            },
            "ja": {
                "title": "フラインバールトルディー",
                "description": "中国のフラインバールトルディー、トアショナトルディー。",
            },
            "ko": {
                "title": "구가づ구가尽尽游子",
                "description": "中国尽尽纳尽游子、尽尽纳尽游子。",
            },
            "vi": {
                "title": "Đểụộđ̉ụếừẹểụẽị",
                "description": "Đểụộđ̉ụếừẹểụẽị、Đểụộđ̉ụếừẹểụẽị。",
            },
        },
    },
    {
        "title": "Magway Sesame Chicken",
        "description": "Pan-roasted chicken coated in toasted sesame.",
        "cuisine": "magway", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("sesame-chicken"),
        "tags": ["chicken", "roast", "classic"],
        "ingredients": [
            {"name": "chicken thighs"},
            {"name": "sesame"},
            {"name": "turmeric"},
            {"name": "garlic"},
            {"name": "soy"},
            {"name": "oil"}
        ],
        "steps": [
            "Marinate chicken.",
            "Pan-roast until golden.",
            "Coat with toasted sesame.",
            "Rest briefly.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "麻格威麻油鸡",
                "description": "用麻油烤鸡,外层覆盖着烤焦的麻子",
            },
            "ja": {
                "title": "マグウェイセサミチキン",
                "description": "セサミ油で焼き上げた鶏肉を、トーストしたセサミで覆う",
            },
            "ko": {
                "title": "마그웨이 세사미 치킨",
                "description": "토스트된 참깨로 덮은 세사미 오일로 구운 치킨",
            },
            "vi": {
                "title": "Gà Sesame Magway",
                "description": "Gà được rán vàng với dầu hạt vừng, phủ hạt vừng rang",
            },
        },
    },
    {
        "title": "Magway Bean Soup",
        "description": "Hearty bean soup from the dry zone.",
        "cuisine": "magway", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("bean-soup-magway"),
        "tags": ["soup", "beans", "comfort"],
        "ingredients": [
            {"name": "yellow beans"},
            {"name": "onion"},
            {"name": "turmeric"},
            {"name": "garlic"},
            {"name": "ginger"},
            {"name": "stock"}
        ],
        "steps": [
            "Soak beans overnight.",
            "Simmer with aromatics.",
            "Mash partially for body.",
            "Season to taste.",
            "Serve hot."
        ],
        "translations": {
            "zh": {
                "title": "马格威豆汤",
                "description": "来自干旱区的浓郁豆汤",
            },
            "ja": {
                "title": "マグウェ豆汤",
                "description": "乾燥地帯からの濃厚豆汁",
            },
            "ko": {
                "title": "마그웨이豆국",
                "description": "건조 지역의濃厚豆국",
            },
            "vi": {
                "title": "Canh đậu Magway",
                "description": "Canh đậu từ vùng khô cằn",
            },
        },
    },
    {
        "title": "Bago Fish Paste Curry",
        "description": "Pungent ngapi curry with pork and vegetables.",
        "cuisine": "bago", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("fish-paste-curry"),
        "tags": ["curry", "pork", "fermented"],
        "ingredients": [
            {"name": "pork"},
            {"name": "ngapi"},
            {"name": "eggplant"},
            {"name": "turmeric"},
            {"name": "chili"},
            {"name": "oil"}
        ],
        "steps": [
            "Fry ngapi paste.",
            "Brown pork.",
            "Add eggplant; simmer.",
            "Finish with chili.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "笫港美米尺席强",
                "description": "笫港美米尺席强一个索尺米尺席强。笫港美米尺席强一个索尺米尺席强、苹果和浦汉的席强.",
            },
            "ja": {
                "title": "バエバンエコヴァト",
                "description": "バエバンエコヴァトは一个索尺米尺席强、苹果和浦汉的席强、エンディントエンエコヴァト.",
            },
            "ko": {
                "title": "구기가개가가가가가가가가가가가가가가가",
                "description": "구기가개가가가가가가가가가가가가가가가가가가가가",
            },
            "vi": {
                "title": "ỉởồợỗụỏụợỏụệỉợị",
                "description": "ỉởồợỗụỏụợỏụệỉợịệỉợịệỏụệỉợịệỏụệỉợịệỏụệ",
            },
        },
    },
    {
        "title": "Bago Palm Sugar Moh",
        "description": "Palm-sugar rice pudding with coconut.",
        "cuisine": "bago", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("palm-sugar-dessert"),
        "tags": ["dessert", "sweet", "classic"],
        "ingredients": [
            {"name": "glutinous rice"},
            {"name": "palm sugar"},
            {"name": "coconut milk"},
            {"name": "salt"},
            {"name": "banana leaf"}
        ],
        "steps": [
            "Cook rice in coconut milk.",
            "Stir in palm sugar.",
            "Steam until set.",
            "Cool in banana leaf cups.",
            "Serve warm or chilled."
        ],
        "translations": {
            "zh": {
                "title": "巴戈棕榈糖米糕",
                "description": "用棕榈糖和椰子做的米糕",
            },
            "ja": {
                "title": "バゴパームシュガーモフ",
                "description": "ココナッツとパームシュガーで作る米菓",
            },
            "ko": {
                "title": "바고팜슈가모프",
                "description": "코코넛과 팜슈가로 만든 쌀죽",
            },
            "vi": {
                "title": "Bago Palm Sugar Mochi",
                "description": "Bánh pudding gạo bằng đường palm và dừa",
            },
        },
    },
    {
        "title": "Bago Tamarind Leaf Curry",
        "description": "Sour curry of young tamarind leaves and fish.",
        "cuisine": "bago", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("tamarind-leaves"),
        "tags": ["curry", "fish", "sour"],
        "ingredients": [
            {"name": "young tamarind leaves"},
            {"name": "fish"},
            {"name": "turmeric"},
            {"name": "garlic"},
            {"name": "chili"},
            {"name": "oil"}
        ],
        "steps": [
            "Blanch tamarind leaves.",
            "Fry fish with turmeric.",
            "Simmer leaves in light gravy.",
            "Adjust sourness.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "巴戈酸豆叶咖喱",
                "description": "用年轻的酸豆叶和鱼制成的酸味咖喱",
            },
            "ja": {
                "title": "バゴタマリンドの葉のカレー",
                "description": "若いタマリンドの葉と魚の酸味カレー",
            },
            "ko": {
                "title": "바고 타마린드 잎 카레",
                "description": "젊은 타마린드 잎과 생선의 신 맛 카레",
            },
            "vi": {
                "title": "Cà ri lá me bago",
                "description": "Món cà ri có vị chua từ lá me non và cá",
            },
        },
    },
    {
        "title": "Sagaing Monastic Curry",
        "description": "Mild vegetable curry from monastery kitchens.",
        "cuisine": "sagaing", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("monastic-curry"),
        "tags": ["curry", "vegetarian", "comfort"],
        "ingredients": [
            {"name": "mixed vegetables"},
            {"name": "turmeric"},
            {"name": "ginger"},
            {"name": "garlic"},
            {"name": "coconut milk"},
            {"name": "oil"}
        ],
        "steps": [
            "Sauté aromatics.",
            "Add vegetables in order of cook time.",
            "Simmer in coconut milk.",
            "Keep flavors gentle.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "王尺席席尺尺尺",
                "description": "三个等索的苹果湿常尺尺",
            },
            "ja": {
                "title": "コエスディントフィート",
                "description": "気尺的苹果湿常尺尺",
            },
            "ko": {
                "title": "총에웕값개가가개가",
                "description": "涕尺的苹果湿常尺尺",
            },
            "vi": {
                "title": "ệạụếụẽợẹủềụế",
                "description": "ệạụếụẽợẹủềụế ᯺ảẽợẹủề",
            },
        },
    },
    {
        "title": "Sagaing Moringa Soup",
        "description": "Light soup of moringa leaves and lentils.",
        "cuisine": "sagaing", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("moringa-soup"),
        "tags": ["soup", "vegetarian", "healthy"],
        "ingredients": [
            {"name": "moringa leaves"},
            {"name": "red lentils"},
            {"name": "turmeric"},
            {"name": "garlic"},
            {"name": "onion"},
            {"name": "stock"}
        ],
        "steps": [
            "Cook lentils until soft.",
            "Add moringa briefly.",
            "Season with turmeric.",
            "Serve hot.",
            "Garnish with fried garlic."
        ],
        "translations": {
            "zh": {
                "title": "尽尽张美漏",
                "description": "美漏给尽尽美和美尽给的死求漏",
            },
            "ja": {
                "title": "コアタントルフィン",
                "description": "フィンにくだはコアタン素にいないだ",
            },
            "ko": {
                "title": "촌촌 안녕세요",
                "description": "안녕세요 촌촌안녕 주가세요",
            },
            "vi": {
                "title": "Sằaing Moringa Soup",
                "description": "Súp nhẹ của lá moringa và đậu lăng",
            },
        },
    },
    {
        "title": "Sagaing Bean Fritters",
        "description": "Crisp split-pea fritters sold at pagoda fairs.",
        "cuisine": "sagaing", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("bean-fritters"),
        "tags": ["fried", "snack", "street food"],
        "ingredients": [
            {"name": "split peas"},
            {"name": "onion"},
            {"name": "turmeric"},
            {"name": "chili"},
            {"name": "oil"},
            {"name": "salt"}
        ],
        "steps": [
            "Soak peas; grind coarse.",
            "Mix with onion and spices.",
            "Drop spoonfuls into hot oil.",
            "Fry until golden.",
            "Drain and serve."
        ],
        "translations": {
            "zh": {
                "title": "撒加英豆腐丸",
                "description": "香脆的豌豆丸子，常在佛塔集市出售",
            },
            "ja": {
                "title": "サガイング豆腐フリッター",
                "description": "パゴダの祭りで売られているシャキシャキの豌豆フリッター",
            },
            "ko": {
                "title": "사가잉콩가루튀김",
                "description": "사원 잔치에서 파는 바삭바삭한 완두콩 튀김",
            },
            "vi": {
                "title": "Bánh rán đậu Sagaing",
                "description": "Bánh rán đậu lăng giòn rụm bán tại hội chùa",
            },
        },
    },
    {
        "title": "Taunggyi Khauk Swe",
        "description": "Shan capital noodles with tomato pork sauce.",
        "cuisine": "taunggyi", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("taunggyi-khauk-swe"),
        "tags": ["noodles", "pork", "classic"],
        "ingredients": [
            {"name": "rice noodles"},
            {"name": "ground pork"},
            {"name": "tomato"},
            {"name": "garlic"},
            {"name": "mustard greens"},
            {"name": "oil"}
        ],
        "steps": [
            "Cook tomato-pork sauce.",
            "Boil noodles.",
            "Toss noodles in sauce.",
            "Top with greens.",
            "Serve immediately."
        ],
        "translations": {
            "zh": {
                "title": "吉尼尼五米",
                "description": "上海尼尼和美尼强漢美永米",
            },
            "ja": {
                "title": "イトェースタープログ",
                "description": "上海尼尼、デスエアサインスタープログ",
            },
            "ko": {
                "title": "촜시재었 었었시었",
                "description": "었었시었 실번 촜시재었 었었시었 었었시었가세요",
            },
            "vi": {
                "title": "Mì Taunggyi Khauk Swe",
                "description": "Mì ễn ệp ệa ệi ệa ệo ệi ệo ệu ệo ệa",
            },
        },
    },
    {
        "title": "Taunggyi Shan Khao Suey",
        "description": "Curried coconut noodle soup with crispy toppings.",
        "cuisine": "taunggyi", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("shan-khao-suey"),
        "tags": ["noodles", "coconut", "comfort"],
        "ingredients": [
            {"name": "egg noodles"},
            {"name": "coconut milk"},
            {"name": "curry powder"},
            {"name": "chicken"},
            {"name": "crispy noodles"},
            {"name": "lime"}
        ],
        "steps": [
            "Simmer coconut curry broth.",
            "Cook chicken and noodles.",
            "Assemble bowls.",
            "Top with crispy noodles.",
            "Serve with lime."
        ],
        "translations": {
            "zh": {
                "title": "給永彬尿尿尿",
                "description": "給永尿尿橋橋尿尿尿尿尿尿尿尿尿尿尿尿",
            },
            "ja": {
                "title": "ディルスメインスアスインスアスインスアス",
                "description": "ディルスメインスアスインスアスインスアスインスアス",
            },
            "ko": {
                "title": "주우었구시었었었었었었었었었었었었었",
                "description": "주우었구시었었었었었었었었었었었었었",
            },
            "vi": {
                "title": "ệẽợệ ỉẽịề ụẽợềụẽềụẽềụẽềụẽềụẽề",
                "description": "ệẽợệ ỉẽịề ụẽợềụẽềụẽềụẽềụẽềụẽềụẽề",
            },
        },
    },
    {
        "title": "Taunggyi Pickled Tea Mix",
        "description": "Snack mix of laphet, nuts, and fried garlic.",
        "cuisine": "taunggyi", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 25, "servings": 4, "image": _img("pickled-tea-snack"),
        "tags": ["snack", "fermented", "classic"],
        "ingredients": [
            {"name": "fermented tea"},
            {"name": "peanuts"},
            {"name": "sesame"},
            {"name": "fried garlic"},
            {"name": "dried shrimp"},
            {"name": "chili"}
        ],
        "steps": [
            "Mix tea leaves with nuts.",
            "Toast sesame.",
            "Fold in fried garlic.",
            "Season with chili.",
            "Serve as snack."
        ],
        "translations": {
            "zh": {
                "title": "王永尽氿常纳",
                "description": "永尽常纳的常纳形尽为纳简常尽和常纳模强",
            },
            "ja": {
                "title": "トィシアビータープロース",
                "description": "トィシアビーター的メコティスはアイコトアショナです",
            },
            "ko": {
                "title": "안이엀 총세요 총세요",
                "description": "안이엀 총세요 총세요 총세요 총세요 총세요 총세요 총세요 총세요",
            },
            "vi": {
                "title": "ễ᭽ụể ễ᭽ụể ễ᭽ụể",
                "description": "ễ᭽ụể ễ᭽ụể ễ᭽ụể ễ᭽ụể ễ᭽ụể ễ᭽ụể",
            },
        },
    },
]
