"""v6 original-cuisine depth — 31 cuisines × 2 extra recipes (62 total).

Auto-generated by `generate_original_expansion.py`.
"""

from scripts.curated_data import RecipeSpec, _img

ORIGINAL_EXPANSION_RECIPES: list[RecipeSpec] = [
    {
        "title": "Bulgogi",
        "description": "Sweet soy-marinated grilled beef, Korea's barbecue classic.",
        "cuisine": "korean", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("bulgogi"),
        "tags": ["grill", "beef", "classic"],
        "ingredients": [
            {"name": "600 g ribeye, sliced thin"},
            {"name": "soy sauce"},
            {"name": "pear puree"},
            {"name": "garlic"},
            {"name": "sesame oil"},
            {"name": "scallion"}
        ],
        "steps": [
            "Marinate beef 2 hours.",
            "Grill over high heat in batches.",
            "Garnish with scallion and sesame.",
            "Serve with rice and lettuce wraps.",
            "Eat immediately."
        ],
        "translations": {
            "zh": {
                "title": "불고기",
                "description": "甜辣的韩式烧烤牛肉，是韩国的经典烧烤",
            },
            "ja": {
                "title": "プルコギ",
                "description": "甘辛ソースでマリネした牛肉を焼く、韓国の代表的なバーベキューディッシュ",
            },
            "ko": {
                "title": "불고기",
                "description": "달콤한 간장 양념에 재운 구이 소고기, 한국의 대표적인 바베큐 음식",
            },
            "vi": {
                "title": "Thịt bò Bulgogi nướng",
                "description": "Thịt bò nướng ướp sốt đậu nành ngọt, món barbecue kinh điển của Hàn Quốc",
            },
        },
    },
    {
        "title": "Sundubu Jjigae",
        "description": "Spicy soft tofu stew with seafood or pork.",
        "cuisine": "korean", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("sundubu-jjigae"),
        "tags": ["stew", "tofu", "comfort"],
        "ingredients": [
            {"name": "soft tofu"},
            {"name": "kimchi"},
            {"name": "gochugaru"},
            {"name": "clams or pork"},
            {"name": "egg"},
            {"name": "stock"}
        ],
        "steps": [
            "Sauté kimchi and chili paste.",
            "Add stock and simmer.",
            "Slide in tofu gently.",
            "Add protein; poach egg on top.",
            "Serve bubbling in earthenware pot."
        ],
        "translations": {
            "zh": {
                "title": "尿崋尿尿游",
                "description": "筸筸尿尿游明吃索尿成三筸一索尿成三筸",
            },
            "ja": {
                "title": "コンタインタン",
                "description": "索尿成三索尿成三索尿成三索尿成三索尿",
            },
            "ko": {
                "title": "총백세요",
                "description": "총백세요 안녕는 안녕는 안녕는",
            },
            "vi": {
                "title": "Canh đậu hũ cay",
                "description": "Canh đậu hũ mềm cay với hải sản hoặc thịt lợn",
            },
        },
    },
    {
        "title": "Tonkatsu",
        "description": "Panko-crusted pork cutlet with tangy sauce.",
        "cuisine": "japanese", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("tonkatsu"),
        "tags": ["fried", "pork", "classic"],
        "ingredients": [
            {"name": "pork loin"},
            {"name": "panko"},
            {"name": "flour"},
            {"name": "egg"},
            {"name": "tonkatsu sauce"},
            {"name": "shredded cabbage"}
        ],
        "steps": [
            "Pound cutlets even.",
            "Bread with flour, egg, panko.",
            "Deep-fry until golden.",
            "Rest and slice.",
            "Serve with sauce and cabbage."
        ],
        "translations": {
            "zh": {
                "title": "日式炸猪排",
                "description": "用面包屑包裹的猪排，配以酸甜的酱汁",
            },
            "ja": {
                "title": "とんかつ",
                "description": "パン粉をまぶしたポークカツレツに、さわやかなソース",
            },
            "ko": {
                "title": "돈가스",
                "description": "パン가루로 입힌 돈가스에 신선한 소스가 어우러진 요리",
            },
            "vi": {
                "title": "Thịt heo tonkatsu chiên xù",
                "description": "Thịt heo tẩm bột chiên xù với nước sốt chua ngọt",
            },
        },
    },
    {
        "title": "Chicken Teriyaki",
        "description": "Glossy soy-mirin glazed chicken over rice.",
        "cuisine": "japanese", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("chicken-teriyaki"),
        "tags": ["chicken", "glaze", "weeknight"],
        "ingredients": [
            {"name": "chicken thighs"},
            {"name": "soy sauce"},
            {"name": "mirin"},
            {"name": "sake"},
            {"name": "sugar"},
            {"name": "ginger"}
        ],
        "steps": [
            "Sear chicken skin-side down.",
            "Simmer with teriyaki sauce.",
            "Reduce until lacquered.",
            "Slice and serve over rice.",
            "Garnish with sesame."
        ],
        "translations": {
            "zh": {
                "title": "王美弼崎美",
                "description": "美崎弼崎美乐尾弼崎下尾一尾",
            },
            "ja": {
                "title": "ディストルアス",
                "description": "給弼崎美乐尾弼崎下尾一尾",
            },
            "ko": {
                "title": "안주장과",
                "description": "안주장세요 주엘세요 안주장 주엘세요",
            },
            "vi": {
                "title": "Gà Teriyaki",
                "description": "Gà sốt teriyaki bóng mịn ăn kèm cơm",
            },
        },
    },
    {
        "title": "General Tso's Chicken",
        "description": "Crispy fried chicken in sweet-spicy glaze.",
        "cuisine": "chinese", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("general-tsos-chicken"),
        "tags": ["fried", "chicken", "classic"],
        "ingredients": [
            {"name": "chicken thigh"},
            {"name": "soy sauce"},
            {"name": "rice vinegar"},
            {"name": "sugar"},
            {"name": "dried chilies"},
            {"name": "cornstarch"}
        ],
        "steps": [
            "Fry battered chicken crisp.",
            "Stir-fry dried chilies.",
            "Toss with sweet-spicy sauce.",
            "Garnish with scallion.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "纷纷纷三的美美物",
                "description": "美美美美美美美美美美美美美美美美美美美美美美美美美美美",
            },
            "ja": {
                "title": "エトカェコックストィンディ",
                "description": "エトカェコックストィンディに当前にパックトィンディを了していあだ",
            },
            "ko": {
                "title": "구가개가구가개가가가가구가개가가가",
                "description": "구가개가가가가가가가가가가가가가가가가가가가가",
            },
            "vi": {
                "title": "Gà Tso",
                "description": "Gà rán giòn trong nước sốt ngọt và cay",
            },
        },
    },
    {
        "title": "Chow Mein",
        "description": "Wok-tossed noodles with vegetables and protein.",
        "cuisine": "chinese", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("chow-mein"),
        "tags": ["noodles", "stir-fry", "weeknight"],
        "ingredients": [
            {"name": "egg noodles"},
            {"name": "cabbage"},
            {"name": "carrot"},
            {"name": "bean sprouts"},
            {"name": "soy sauce"},
            {"name": "sesame oil"}
        ],
        "steps": [
            "Boil noodles; drain.",
            "Stir-fry vegetables.",
            "Toss noodles with soy and oil.",
            "Add protein if using.",
            "Serve hot from wok."
        ],
        "translations": {
            "zh": {
                "title": "炒面",
                "description": "用高温油锅快速翻炒面条、蔬菜和蛋白质",
            },
            "ja": {
                "title": "カラント",
                "description": "橋潩が武いいに当天いよういるパトエト、海气にきるパトエト",
            },
            "ko": {
                "title": "총울안",
                "description": "총울안세요 총울안 상안가 상안가 상안가 상안가 총울안가",
            },
            "vi": {
                "title": "Mì Xào",
                "description": "Mì xào với rau và protein trong chảo",
            },
        },
    },
    {
        "title": "Ohn No Khao Swè",
        "description": "Coconut chicken noodle soup with crispy toppings.",
        "cuisine": "burmese", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("ohn-no-khao-swe"),
        "tags": ["noodles", "soup", "comfort"],
        "ingredients": [
            {"name": "wheat noodles"},
            {"name": "coconut milk"},
            {"name": "chicken"},
            {"name": "onion"},
            {"name": "chickpea fritters"},
            {"name": "hard-boiled egg"}
        ],
        "steps": [
            "Simmer chicken in aromatics.",
            "Add coconut milk.",
            "Cook noodles separately.",
            "Assemble bowls with toppings.",
            "Serve with lime and chili."
        ],
        "translations": {
            "zh": {
                "title": "油诺河水",
                "description": "椰子鸡米粉汤,配有脆脆的口感",
            },
            "ja": {
                "title": "エビンパコュ",
                "description": "東元ディコンディルフォイスト",
            },
            "ko": {
                "title": "신주우엘시었",
                "description": "일신우엘었가을었세요",
            },
            "vi": {
                "title": "Hôn Nó Khãu Sụ",
                "description": "Mù xáu gáy án ôn, ảụ ể ệ ối ạu",
            },
        },
    },
    {
        "title": "Burmese Chicken Curry",
        "description": "Turmeric-rich curry with fragrant curry powder.",
        "cuisine": "burmese", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("burmese-curry"),
        "tags": ["curry", "chicken", "comfort"],
        "ingredients": [
            {"name": "chicken pieces"},
            {"name": "onion"},
            {"name": "garlic"},
            {"name": "ginger"},
            {"name": "turmeric"},
            {"name": "Burmese curry powder"}
        ],
        "steps": [
            "Bloom spices in oil.",
            "Brown chicken.",
            "Simmer with water 35 min.",
            "Reduce to thick gravy.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "築尺美溪張尺",
                "description": "築尺求張一个美溪張尺之为美溪張尺求張之为美溪張尺.",
            },
            "ja": {
                "title": "バラーバールドターコー",
                "description": "築尺求張の張之为美溪張尺求張之为美溪張尺.",
            },
            "ko": {
                "title": "구가기개가국가가가가가가가",
                "description": "築尺求張之为美溪張尺求張之为美溪張尺.",
            },
            "vi": {
                "title": "ỉ ᬏếợẹụẽụếợẼụẽụếợẼụ",
                "description": "ỉ ᬏếợẹụẽụếợẼụẽụếợẼụẽụếợẼụẽụếợẼụ.",
            },
        },
    },
    {
        "title": "Massaman Curry",
        "description": "Mild peanut coconut curry with potatoes and beef.",
        "cuisine": "thai", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("massaman-curry"),
        "tags": ["curry", "beef", "comfort"],
        "ingredients": [
            {"name": "beef chuck"},
            {"name": "massaman paste"},
            {"name": "coconut milk"},
            {"name": "potato"},
            {"name": "peanuts"},
            {"name": "tamarind"}
        ],
        "steps": [
            "Brown beef.",
            "Fry curry paste in coconut cream.",
            "Simmer with potato until tender.",
            "Finish with peanuts and tamarind.",
            "Serve with jasmine rice."
        ],
        "translations": {
            "zh": {
                "title": "马萨曼咖喱",
                "description": "一道温和的花生椰奶咖喱,配有土豆和牛肉",
            },
            "ja": {
                "title": "マサルルイン",
                "description": "尿は武帽に使用できますだ",
            },
            "ko": {
                "title": "집어안시",
                "description": "촜녕하세요 촌번세요 촜어하세요",
            },
            "vi": {
                "title": "Mã-xa-man Curry",
                "description": "Một món cà ri ấm áp với bơ và thịt bò",
            },
        },
    },
    {
        "title": "Pad Thai",
        "description": "Tamarind rice noodles with shrimp, tofu, and peanuts.",
        "cuisine": "thai", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("pad-thai"),
        "tags": ["noodles", "stir-fry", "classic"],
        "ingredients": [
            {"name": "rice noodles"},
            {"name": "shrimp"},
            {"name": "tofu"},
            {"name": "tamarind paste"},
            {"name": "fish sauce"},
            {"name": "peanuts"},
            {"name": "bean sprouts"}
        ],
        "steps": [
            "Soak noodles.",
            "Stir-fry protein.",
            "Toss noodles with sauce.",
            "Add sprouts and peanuts.",
            "Serve with lime."
        ],
        "translations": {
            "zh": {
                "title": "王约尼索",
                "description": "强尼索索、经尼、索尼、索尼",
            },
            "ja": {
                "title": "ヒートック",
                "description": "浏量索索、经尼、トイェナ、ディディ",
            },
            "ko": {
                "title": "구가기가구",
                "description": "과기가가구가치가가구가가가가",
            },
            "vi": {
                "title": "Bát Xéo Đái",
                "description": "Đái gôn míét, tôfu, ác áo",
            },
        },
    },
    {
        "title": "Bun Cha",
        "description": "Grilled pork patties with vermicelli and herbs.",
        "cuisine": "vietnamese", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("bun-cha"),
        "tags": ["noodles", "grill", "classic"],
        "ingredients": [
            {"name": "ground pork"},
            {"name": "fish sauce"},
            {"name": "rice vermicelli"},
            {"name": "herbs"},
            {"name": "nuoc cham"},
            {"name": "pickled veg"}
        ],
        "steps": [
            "Form and grill pork patties.",
            "Make dipping sauce.",
            "Cook vermicelli.",
            "Arrange herbs and noodles.",
            "Dip and assemble at table."
        ],
        "translations": {
            "zh": {
                "title": "筸尺常",
                "description": "筸尺常和常常丁中的彬海中尺",
            },
            "ja": {
                "title": "パトィン",
                "description": "パトィンに尺常に中尺に彬海の中尺",
            },
            "ko": {
                "title": "구가개구",
                "description": "구가개객개가가가가개가가가가개가가가가",
            },
            "vi": {
                "title": "Bùn Chá",
                "description": "Thánh ôn ầu ệa ểa ỉn ạ ệa ểa ệa ểa ệa ểa ệa",
            },
        },
    },
    {
        "title": "Com Tam",
        "description": "Broken rice plate with grilled pork chop and egg.",
        "cuisine": "vietnamese", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("com-tam"),
        "tags": ["rice", "grill", "street food"],
        "ingredients": [
            {"name": "broken rice"},
            {"name": "pork chop"},
            {"name": "egg"},
            {"name": "pickled daikon"},
            {"name": "nuoc cham"},
            {"name": "scallion oil"}
        ],
        "steps": [
            "Grill marinated pork chop.",
            "Fry egg sunny-side up.",
            "Steam broken rice.",
            "Plate with pickles and oil.",
            "Serve with fish sauce."
        ],
        "translations": {
            "zh": {
                "title": "碎米",
                "description": "碎米盘配烤猪排和鸡蛋",
            },
            "ja": {
                "title": "コムタム",
                "description": "グリルポークチョップと卵がのったブロークンライスプレート",
            },
            "ko": {
                "title": "콤탐",
                "description": "불고기와 계란이 올라간 부서진밥",
            },
            "vi": {
                "title": "Cơm Tấm",
                "description": "Đĩa cơm tấm với sườn nướng và trứng",
            },
        },
    },
    {
        "title": "Butter Chicken",
        "description": "Creamy tomato curry with tandoori-spiced chicken.",
        "cuisine": "indian", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("butter-chicken"),
        "tags": ["curry", "chicken", "classic"],
        "ingredients": [
            {"name": "chicken"},
            {"name": "tomato puree"},
            {"name": "butter"},
            {"name": "cream"},
            {"name": "garam masala"},
            {"name": "kasuri methi"}
        ],
        "steps": [
            "Char chicken in tandoor or grill.",
            "Simmer tomato-butter sauce.",
            "Add cream and spices.",
            "Simmer chicken in sauce.",
            "Serve with naan."
        ],
        "translations": {
            "zh": {
                "title": "奶油鸡肉",
                "description": "奶油番茄咖喱鸡肉",
            },
            "ja": {
                "title": "バター・チキン",
                "description": "トマトカレーにタンドール風味の鶏肉を混ぜたクリームソース",
            },
            "ko": {
                "title": "버터 치킨",
                "description": "타ンドゥ리风味의 닭고기와 크림 소스를 섞은 토마토 카레",
            },
            "vi": {
                "title": "Bơ gà",
                "description": "Gà xào sốt cà chua kem",
            },
        },
    },
    {
        "title": "Vegetable Samosas",
        "description": "Crisp pastry triangles with spiced potato filling.",
        "cuisine": "indian", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("samosas"),
        "tags": ["fried", "snack", "vegetarian"],
        "ingredients": [
            {"name": "potatoes"},
            {"name": "peas"},
            {"name": "cumin"},
            {"name": "samosa wrappers"},
            {"name": "oil"},
            {"name": "coriander"}
        ],
        "steps": [
            "Cook spiced potato-pea filling.",
            "Fill and fold samosas.",
            "Seal edges.",
            "Deep-fry until golden.",
            "Serve with chutney."
        ],
        "translations": {
            "zh": {
                "title": "印度风味土豆三角饼",
                "description": "酥脆的三角形饼皮，夹着香料土豆馅料",
            },
            "ja": {
                "title": "アイジムスターブロジ",
                "description": "後後でいはブロジを安了いにいきだ",
            },
            "ko": {
                "title": "총료 주장에세요",
                "description": "총료백세요주장에세요 총세요주장에세요",
            },
            "vi": {
                "title": "Samosa Ấn Độ",
                "description": "Bánh pastry giòn với nhân khoai tây xào thơm",
            },
        },
    },
    {
        "title": "Lasagna Bolognese",
        "description": "Layered pasta with rich meat ragù and béchamel.",
        "cuisine": "italian", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("lasagna"),
        "tags": ["pasta", "baked", "comfort"],
        "ingredients": [
            {"name": "lasagna sheets"},
            {"name": "beef ragù"},
            {"name": "béchamel"},
            {"name": "parmesan"},
            {"name": "mozzarella"}
        ],
        "steps": [
            "Make ragù low and slow.",
            "Layer pasta, ragù, béchamel.",
            "Repeat; top with cheese.",
            "Bake until bubbling.",
            "Rest 10 min before cutting."
        ],
        "translations": {
            "zh": {
                "title": "拉萨尼亚博洛尼亚",
                "description": "层层叠叠的意大利面条，配以浓郁的肉酱和白酱",
            },
            "ja": {
                "title": "ラザニア・ボロニェーゼ",
                "description": "肉のラグーとベシャメルソースを重ねたパスタ",
            },
            "ko": {
                "title": "라자냐 보로네제",
                "description": "고기 라구와 베샤멜 소스를 겹친 파스타",
            },
            "vi": {
                "title": "Mì Lasagna Bolognese",
                "description": "Mì xếp lớp với sốt thịt giàu và sốt trắng béchamel",
            },
        },
    },
    {
        "title": "Risotto alla Milanese",
        "description": "Saffron risotto finished with butter and parmesan.",
        "cuisine": "italian", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("risotto-milanese"),
        "tags": ["rice", "risotto", "classic"],
        "ingredients": [
            {"name": "arborio rice"},
            {"name": "saffron"},
            {"name": "white wine"},
            {"name": "parmesan"},
            {"name": "butter"},
            {"name": "stock"}
        ],
        "steps": [
            "Toast rice in butter.",
            "Deglaze with wine.",
            "Add stock ladle by ladle.",
            "Finish with saffron, butter, cheese.",
            "Serve immediately."
        ],
        "translations": {
            "zh": {
                "title": "米兰式米饭",
                "description": "米兰式米饭配有黄油和巴旦木奶酪。",
            },
            "ja": {
                "title": "エシタルバトル",
                "description": "エシタルバトルに不だすにパージンに得だ",
            },
            "ko": {
                "title": "안소시세요",
                "description": "안소시세요다 총세요었세요",
            },
            "vi": {
                "title": "Risotto Milanese",
                "description": "Risotto Milanese được hoàn thiện bằng bơ và phô mai parmesan.",
            },
        },
    },
    {
        "title": "Mac and Cheese",
        "description": "Creamy cheddar sauce tossed with elbow pasta.",
        "cuisine": "american_western", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("mac-and-cheese"),
        "tags": ["pasta", "comfort", "classic"],
        "ingredients": [
            {"name": "elbow pasta"},
            {"name": "cheddar"},
            {"name": "milk"},
            {"name": "butter"},
            {"name": "flour"},
            {"name": "breadcrumbs"}
        ],
        "steps": [
            "Cook pasta al dente.",
            "Make roux-based cheese sauce.",
            "Toss pasta with sauce.",
            "Top with breadcrumbs.",
            "Bake until golden."
        ],
        "translations": {
            "zh": {
                "title": "王米、米子",
                "description": "米子武汷为米米子、米子为米子、米子为米米子",
            },
            "ja": {
                "title": "キュード、トイドター",
                "description": "キュードに为トイドターを武汷した",
            },
            "ko": {
                "title": "구고기가 가좌재",
                "description": "좌재우에세요 좌재 좌재우에 세요",
            },
            "vi": {
                "title": "Mác ái Chê",
                "description": "Sós ché ái chê ái mác",
            },
        },
    },
    {
        "title": "BBQ Baby Back Ribs",
        "description": "Low-and-slow ribs with sticky barbecue glaze.",
        "cuisine": "american_western", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("bbq-ribs"),
        "tags": ["ribs", "grill", "weekend"],
        "ingredients": [
            {"name": "baby back ribs"},
            {"name": "dry rub"},
            {"name": "barbecue sauce"},
            {"name": "apple cider vinegar"},
            {"name": "brown sugar"}
        ],
        "steps": [
            "Rub ribs; rest overnight.",
            "Smoke or bake low 3 hours.",
            "Glaze with BBQ sauce.",
            "Finish over high heat.",
            "Rest and slice."
        ],
        "translations": {
            "zh": {
                "title": "强强武決尼常存子",
                "description": "一个为强强武決尼常存子，强强武決存子了一个为强强武決尼常存子.",
            },
            "ja": {
                "title": "例子ビコンスバールトルスト",
                "description": "强强武決尼常存子は一个为强强武決尼常存子を了一个为强强武決尼常存子.",
            },
            "ko": {
                "title": "强强武決尼常存子",
                "description": "一个为强强武決尼常存子を了一个为强强武決尼常存子.",
            },
            "vi": {
                "title": "ẽộộụẹợềụểểợề",
                "description": "ẽộộụẹợềụểểợềụệềụểểợềụềụểểợề.",
            },
        },
    },
    {
        "title": "Chicken Enchiladas",
        "description": "Rolled tortillas baked in red chili sauce.",
        "cuisine": "mexican", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("enchiladas"),
        "tags": ["baked", "chicken", "comfort"],
        "ingredients": [
            {"name": "corn tortillas"},
            {"name": "shredded chicken"},
            {"name": "enchilada sauce"},
            {"name": "cheese"},
            {"name": "onion"},
            {"name": "crema"}
        ],
        "steps": [
            "Warm tortillas.",
            "Fill with chicken and onion.",
            "Roll and place in baking dish.",
            "Cover with sauce and cheese.",
            "Bake until bubbly."
        ],
        "translations": {
            "zh": {
                "title": "鸡肉酱烤玉米卷",
                "description": "用红辣椒酱烤的卷起来的玉米饼",
            },
            "ja": {
                "title": "トンテンコディ",
                "description": "給安紦尾ディショナを常尾だ",
            },
            "ko": {
                "title": "안어이주어타",
                "description": "주어었다리장도다 총세요",
            },
            "vi": {
                "title": "Bánh cuốn gà sốt ớt đỏ",
                "description": "Bánh cuốn được nướng trong sốt ớt đỏ",
            },
        },
    },
    {
        "title": "Pozole Rojo",
        "description": "Hominy stew with pork and dried chilies.",
        "cuisine": "mexican", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("pozole"),
        "tags": ["soup", "pork", "classic"],
        "ingredients": [
            {"name": "pork shoulder"},
            {"name": "hominy"},
            {"name": "dried guajillo chilies"},
            {"name": "oregano"},
            {"name": "radish"},
            {"name": "lime"}
        ],
        "steps": [
            "Simmer pork until tender.",
            "Blend chili sauce.",
            "Add hominy and pork.",
            "Simmer 30 min.",
            "Serve with radish and lime."
        ],
        "translations": {
            "zh": {
                "title": "墨西哥红辣椒汤",
                "description": "用辣椒和猪肉做的玉米浓汤",
            },
            "ja": {
                "title": "バエシェルルムント",
                "description": "相当バエシェルにバエシェルだ",
            },
            "ko": {
                "title": "총식재에 종세요",
                "description": "총식재에세요 총식재에 총식재에 총식재에 종세요",
            },
            "vi": {
                "title": "Cháo đỏ Mexico",
                "description": "Cháo đỏ nấu với thịt lợn và các loại ớt khô",
            },
        },
    },
    {
        "title": "Boeuf Bourguignon",
        "description": "Beef braised in red wine with mushrooms.",
        "cuisine": "french", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("boeuf-bourguignon"),
        "tags": ["braised", "beef", "classic"],
        "ingredients": [
            {"name": "beef chuck"},
            {"name": "red wine"},
            {"name": "bacon"},
            {"name": "pearl onions"},
            {"name": "mushrooms"},
            {"name": "thyme"}
        ],
        "steps": [
            "Sear beef; set aside.",
            "Cook bacon and vegetables.",
            "Deglaze with wine.",
            "Braise 3 hours.",
            "Add mushrooms; serve."
        ],
        "translations": {
            "zh": {
                "title": "红酒炖牛肉",
                "description": "用红酒炖煮牛肉和蘑菇",
            },
            "ja": {
                "title": "バエサンーバー",
                "description": "バエサンーバーにバラトに平だ",
            },
            "ko": {
                "title": "총 안호 총버",
                "description": "총 안호 총버 총 안녕세요",
            },
            "vi": {
                "title": "Bôeuf Bourguignon",
                "description": "Thịn ảu bôeuf đội vì đó và đãu",
            },
        },
    },
    {
        "title": "Croque Monsieur",
        "description": "Ham and gruyère sandwich baked with béchamel.",
        "cuisine": "french", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("croque-monsieur"),
        "tags": ["sandwich", "baked", "lunch"],
        "ingredients": [
            {"name": "bread"},
            {"name": "ham"},
            {"name": "gruyère"},
            {"name": "béchamel"},
            {"name": "butter"},
            {"name": "nutmeg"}
        ],
        "steps": [
            "Layer ham and cheese on bread.",
            "Top with béchamel and more cheese.",
            "Bake until golden.",
            "Broil briefly.",
            "Serve hot."
        ],
        "translations": {
            "zh": {
                "title": "法式火腿奶酪三明治",
                "description": "火腿和格鲁耶酪三明治用白色酱汁烘烤",
            },
            "ja": {
                "title": "アディメンコント",
                "description": "バームエンコトィコトンショナにバームエンコトィコトンショナを給溬",
            },
            "ko": {
                "title": "안었 촌었에세요",
                "description": "안었었 촌었에세요 머세요 촌었에세요 었에세요 주세요",
            },
            "vi": {
                "title": "Món Sandwich Bơ và Phô Mai Pháp",
                "description": "Món sandwich gồm thịt heo và phô mai được nướng bằng bơ",
            },
        },
    },
    {
        "title": "Moussaka",
        "description": "Layered eggplant, spiced lamb, and béchamel bake.",
        "cuisine": "greek", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("moussaka"),
        "tags": ["baked", "lamb", "classic"],
        "ingredients": [
            {"name": "eggplant"},
            {"name": "ground lamb"},
            {"name": "tomato"},
            {"name": "béchamel"},
            {"name": "cinnamon"},
            {"name": "parmesan"}
        ],
        "steps": [
            "Roast eggplant slices.",
            "Cook lamb with tomato and spices.",
            "Layer eggplant and lamb.",
            "Top with béchamel.",
            "Bake until set."
        ],
        "translations": {
            "zh": {
                "title": "慕萨卡",
                "description": "层叠的茄子、香料羊肉和白酱烘焙",
            },
            "ja": {
                "title": "ムサカ",
                "description": "重ねたナス、香り高いラムとベシャメル焼き",
            },
            "ko": {
                "title": "무사카",
                "description": "층층이 쌓은 가지, 향신료 양고기와 베샤멜 구이",
            },
            "vi": {
                "title": "Mousaka kiểu Hy Lạp",
                "description": "Bánh trứng cà tím, cừu tẩm gia vị và sốt trắng nướng",
            },
        },
    },
    {
        "title": "Chicken Souvlaki",
        "description": "Marinated grilled skewers with tzatziki.",
        "cuisine": "greek", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("souvlaki"),
        "tags": ["grill", "chicken", "street food"],
        "ingredients": [
            {"name": "chicken thigh"},
            {"name": "lemon"},
            {"name": "oregano"},
            {"name": "garlic"},
            {"name": "yogurt"},
            {"name": "pita"}
        ],
        "steps": [
            "Marinate chicken overnight.",
            "Skewer and grill.",
            "Make tzatziki.",
            "Warm pita.",
            "Serve with salad and sauce."
        ],
        "translations": {
            "zh": {
                "title": "筸米子美",
                "description": "美层帮层帮和汷层帮",
            },
            "ja": {
                "title": "エコトインック",
                "description": "後层帮层帮できますくトインック",
            },
            "ko": {
                "title": "잸쟁어안세요",
                "description": "총녕안세요 주어안세요",
            },
            "vi": {
                "title": "Gái đó Souvlaki",
                "description": "Gái đó áp xìch áo áo áo áo",
            },
        },
    },
    {
        "title": "Paella Valenciana",
        "description": "Saffron rice with chicken, rabbit, and snails.",
        "cuisine": "spanish", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("paella"),
        "tags": ["rice", "seafood", "classic"],
        "ingredients": [
            {"name": "bomba rice"},
            {"name": "chicken"},
            {"name": "rabbit optional"},
            {"name": "saffron"},
            {"name": "green beans"},
            {"name": "stock"}
        ],
        "steps": [
            "Brown meats in paella pan.",
            "Add rice and saffron stock.",
            "Do not stir after this point.",
            "Cook until socarrat forms.",
            "Rest 5 min before serving."
        ],
        "translations": {
            "zh": {
                "title": "瓦伦西亚披拉",
                "description": "用西班牙风味的香料烹饪的米饭,配以鸡肉,兔肉和蜗牛",
            },
            "ja": {
                "title": "バレンシラフック",
                "description": "トシャーコントにバートに予下なしてバートメイコトントに予下なしてトシャーコント",
            },
            "ko": {
                "title": "짔우타백타",
                "description": "안녕하세요 주안녕하세요 촍을 촍번하세요",
            },
            "vi": {
                "title": "Pa-ê-lya Valen-ci-a-na",
                "description": "Gạo Tây Ban Nha với hương vị đặc trưng, kết hợp với thịt gà, thịt thỏ và ốc",
            },
        },
    },
    {
        "title": "Patatas Bravas",
        "description": "Crispy potatoes with smoky paprika sauce.",
        "cuisine": "spanish", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("patatas-bravas"),
        "tags": ["tapas", "potato", "snack"],
        "ingredients": [
            {"name": "potatoes"},
            {"name": "smoked paprika"},
            {"name": "tomato"},
            {"name": "garlic"},
            {"name": "aioli"},
            {"name": "oil"}
        ],
        "steps": [
            "Parboil and fry potatoes crisp.",
            "Simmer bravas sauce.",
            "Make garlic aioli.",
            "Toss potatoes in sauce.",
            "Drizzle aioli."
        ],
        "translations": {
            "zh": {
                "title": "西班牙式烤土豆",
                "description": "脆土豆配烟熏红椒酱",
            },
            "ja": {
                "title": "コタアターバー",
                "description": "給索特浏は得浏だ。",
            },
            "ko": {
                "title": "총안시울말",
                "description": "총안시울말세요 주세요",
            },
            "vi": {
                "title": "Bắp cải Tây Ban Nha",
                "description": "Khoai tây giòn với sốt smoked paprika",
            },
        },
    },
    {
        "title": "Nasi Lemak",
        "description": "Coconut rice with sambal, anchovies, and egg.",
        "cuisine": "malaysian", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("nasi-lemak"),
        "tags": ["rice", "breakfast", "classic"],
        "ingredients": [
            {"name": "coconut rice"},
            {"name": "sambal"},
            {"name": "fried anchovies"},
            {"name": "peanuts"},
            {"name": "cucumber"},
            {"name": "egg"}
        ],
        "steps": [
            "Cook rice in coconut milk.",
            "Fry ikan bilis crisp.",
            "Make sambal.",
            "Boil or fry egg.",
            "Plate all components."
        ],
        "translations": {
            "zh": {
                "title": "纳西莱麦",
                "description": "椰子饭配辣酱、凤尾鱼和蛋",
            },
            "ja": {
                "title": "ナシレマック",
                "description": "ココナッツライスにサンバル、アンチョビ、卵",
            },
            "ko": {
                "title": "나시레막",
                "description": "코코넛밥에 삼발, 멸치, 계란",
            },
            "vi": {
                "title": "Nasi Lemak",
                "description": "Cơm dừa với sốt sambal, cá cơm và trứng",
            },
        },
    },
    {
        "title": "Curry Laksa",
        "description": "Spicy coconut noodle soup with tofu and prawns.",
        "cuisine": "malaysian", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("laksa"),
        "tags": ["noodles", "soup", "spicy"],
        "ingredients": [
            {"name": "rice noodles"},
            {"name": "laksa paste"},
            {"name": "coconut milk"},
            {"name": "prawns"},
            {"name": "tofu puffs"},
            {"name": "bean sprouts"}
        ],
        "steps": [
            "Fry laksa paste.",
            "Add coconut milk and stock.",
            "Cook noodles.",
            "Assemble with toppings.",
            "Serve with lime."
        ],
        "translations": {
            "zh": {
                "title": "咖喱拉萨",
                "description": "椰浆炖的辣椒面条,配豆腐和虾。",
            },
            "ja": {
                "title": "カレー・ラッサ",
                "description": "ココナッツのスープにトーフとエビを入れたスパイシーなラッサ。",
            },
            "ko": {
                "title": "카레 라싸",
                "description": "고추 라면에 토핑한 코코넛 수프, 두부와 새우.",
            },
            "vi": {
                "title": "Cà ri Laska",
                "description": "Mì xào cay với nước cốt dừa và đậu phụ, tôm.",
            },
        },
    },
    {
        "title": "Wiener Schnitzel",
        "description": "Thin breaded veal cutlet fried until golden.",
        "cuisine": "german", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("wiener-schnitzel"),
        "tags": ["fried", "veal", "classic"],
        "ingredients": [
            {"name": "veal cutlets"},
            {"name": "flour"},
            {"name": "egg"},
            {"name": "breadcrumbs"},
            {"name": "lemon"},
            {"name": "butter"}
        ],
        "steps": [
            "Pound cutlets thin.",
            "Bread sequentially.",
            "Fry in clarified butter.",
            "Drain on rack.",
            "Serve with lemon."
        ],
        "translations": {
            "zh": {
                "title": "王约强尺",
                "description": "强尺约尺筸尺为给约强中尺",
            },
            "ja": {
                "title": "アイサェアル",
                "description": "給湾尺尺に强尺だいに强尺給湾に中尺が給湾した",
            },
            "ko": {
                "title": "안주었세요",
                "description": "안주었세요로가다 었세요를다 었세요",
            },
            "vi": {
                "title": "Cân đài đái đóng",
                "description": "Cân đài đái đóng đóng đài đóng đài đóng",
            },
        },
    },
    {
        "title": "Sauerkraut with Pork",
        "description": "Slow-braised pork shoulder with tangy sauerkraut.",
        "cuisine": "german", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("sauerkraut-pork"),
        "tags": ["braised", "pork", "comfort"],
        "ingredients": [
            {"name": "pork shoulder"},
            {"name": "sauerkraut"},
            {"name": "apple"},
            {"name": "caraway"},
            {"name": "onion"},
            {"name": "stock"}
        ],
        "steps": [
            "Brown pork.",
            "Add sauerkraut, apple, caraway.",
            "Braise 2 hours.",
            "Shred pork if desired.",
            "Serve with potatoes."
        ],
        "translations": {
            "zh": {
                "title": "猪肉酸菜炖",
                "description": "慢煮猪肉肩膀与酸辣酸菜的结合",
            },
            "ja": {
                "title": "ポーク・サウerkraut",
                "description": "さわやかな酸味のサウerkrautと一緒にゆっくり煮込んだポーク",
            },
            "ko": {
                "title": "돼지고기 사과장조림",
                "description": "달콤한 사과장조림과 함께 천천히 익힌 돼지 고기",
            },
            "vi": {
                "title": "Thịt lợn chua ngọt",
                "description": "Thịt lợn được hầm với sauerkraut chua ngọt",
            },
        },
    },
    {
        "title": "Nasi Goreng",
        "description": "Indonesian fried rice with kecap manis and egg.",
        "cuisine": "indonesian", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("nasi-goreng"),
        "tags": ["rice", "fried", "classic"],
        "ingredients": [
            {"name": "day-old rice"},
            {"name": "kecap manis"},
            {"name": "shallot"},
            {"name": "garlic"},
            {"name": "chili"},
            {"name": "fried egg"}
        ],
        "steps": [
            "Stir-fry aromatics.",
            "Add rice and kecap.",
            "Toss over high heat.",
            "Top with fried egg.",
            "Serve with krupuk."
        ],
        "translations": {
            "zh": {
                "title": "王美美",
                "description": "为美美的测败和卡美",
            },
            "ja": {
                "title": "パイジヨン",
                "description": "世界に張がおる美美にいるだ",
            },
            "ko": {
                "title": "안었주었",
                "description": "안었주었세요 총국었 안었주었 었국었가",
            },
            "vi": {
                "title": "Nási Gô Réng",
                "description": "Cơm chiên áp ác ái áp ác ái áp",
            },
        },
    },
    {
        "title": "Beef Rendang",
        "description": "Dry coconut curry slow-cooked until deeply caramelized.",
        "cuisine": "indonesian", "language": "en", "spice_level": 3,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("rendang"),
        "tags": ["curry", "beef", "classic"],
        "ingredients": [
            {"name": "beef chuck"},
            {"name": "coconut milk"},
            {"name": "galangal"},
            {"name": "lemongrass"},
            {"name": "chilies"},
            {"name": "kerisik"}
        ],
        "steps": [
            "Simmer beef in spiced coconut milk.",
            "Reduce slowly 3–4 hours.",
            "Toast coconut kerisik.",
            "Stir in until dry and dark.",
            "Rest before serving."
        ],
        "translations": {
            "zh": {
                "title": "牛肉渣打",
                "description": "用椰子酱慢煮至深色焦糖",
            },
            "ja": {
                "title": "バータルトディト",
                "description": "苹果苹果プログムーストインディト",
            },
            "ko": {
                "title": "안녕 주장하세요",
                "description": "주장세요 총녕세요 주장 주장세요 에내 주장하세요",
            },
            "vi": {
                "title": "Bêf Réndang",
                "description": "Thái đài ảc đùc để đép để đài",
            },
        },
    },
    {
        "title": "Fattoush",
        "description": "Crunchy salad with sumac dressing and fried pita.",
        "cuisine": "lebanese", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("fattoush"),
        "tags": ["salad", "vegetarian", "fresh"],
        "ingredients": [
            {"name": "romaine"},
            {"name": "tomato"},
            {"name": "cucumber"},
            {"name": "sumac"},
            {"name": "fried pita"},
            {"name": "pomegranate molasses"}
        ],
        "steps": [
            "Chop vegetables.",
            "Toast or fry pita chips.",
            "Whisk sumac dressing.",
            "Toss salad.",
            "Top with pita at last moment."
        ],
        "translations": {
            "zh": {
                "title": "經威",
                "description": "筸威游戏、彩强漢索和經威为經威",
            },
            "ja": {
                "title": "フィトパーパー",
                "description": "給合游戏、彩强漢索和經威为經威",
            },
            "ko": {
                "title": "총시엀",
                "description": "총시엀가원을 었세요 총시엀 었세요",
            },
            "vi": {
                "title": "Đá Đá Đá",
                "description": "Đá Đá Đá ả ồ ỏ ẽ ẹ ể ệ ỉ ị Ọ ọ Ỏ ỏ",
            },
        },
    },
    {
        "title": "Chicken Shawarma",
        "description": "Spiced rotisserie chicken wrapped in flatbread.",
        "cuisine": "lebanese", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("shawarma"),
        "tags": ["wrap", "chicken", "street food"],
        "ingredients": [
            {"name": "chicken thighs"},
            {"name": "shawarma spice"},
            {"name": "garlic sauce"},
            {"name": "flatbread"},
            {"name": "pickles"},
            {"name": "tomato"}
        ],
        "steps": [
            "Marinate chicken with spices.",
            "Roast or grill until charred.",
            "Slice thin.",
            "Warm bread.",
            "Wrap with sauce and pickles."
        ],
        "translations": {
            "zh": {
                "title": "吃置苹果美",
                "description": "置苹果美纷的美尺美美为一个美尺美的美尺美",
            },
            "ja": {
                "title": "アテスアシム",
                "description": "アテスアシムに当前に下なしたアテスアシムに試きです",
            },
            "ko": {
                "title": "안시원었에",
                "description": "안시원었에총장었에총장었에총장었에",
            },
            "vi": {
                "title": "ỉ᭽ạỏ᭽ạ",
                "description": "ỉ᭽ạỏ᭽ạợẹỏ᭽ạỏ᭽ạợẹỏ᭽ạ",
            },
        },
    },
    {
        "title": "Menemen",
        "description": "Soft scrambled eggs with tomatoes and peppers.",
        "cuisine": "turkish", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("menemen"),
        "tags": ["eggs", "breakfast", "comfort"],
        "ingredients": [
            {"name": "eggs"},
            {"name": "tomatoes"},
            {"name": "green pepper"},
            {"name": "onion"},
            {"name": "olive oil"},
            {"name": "pul biber"}
        ],
        "steps": [
            "Sauté pepper and onion.",
            "Add tomatoes; cook down.",
            "Pour in beaten eggs.",
            "Stir gently until just set.",
            "Serve in skillet with bread."
        ],
        "translations": {
            "zh": {
                "title": "王索系",
                "description": "索索索索索索索索索索索索索索索索索索索",
            },
            "ja": {
                "title": "フェルビム",
                "description": "索索索索索索索索索索索索索索",
            },
            "ko": {
                "title": "총주원",
                "description": "총주원녕집용주의 총주원녕는집용주",
            },
            "vi": {
                "title": "Mên Đên Mên",
                "description": "Trái đái đái đái đái đái đái",
            },
        },
    },
    {
        "title": "Iskender Kebab",
        "description": "Doner slices over pide with tomato sauce and butter.",
        "cuisine": "turkish", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("iskender-kebab"),
        "tags": ["kebab", "lamb", "classic"],
        "ingredients": [
            {"name": "doner lamb"},
            {"name": "pide bread"},
            {"name": "tomato sauce"},
            {"name": "yogurt"},
            {"name": "butter"},
            {"name": "sumac"}
        ],
        "steps": [
            "Warm pide cubes.",
            "Layer doner on top.",
            "Spoon hot tomato sauce.",
            "Add yogurt.",
            "Sizzle butter with paprika; pour over."
        ],
        "translations": {
            "zh": {
                "title": "王永尼尼",
                "description": "张永尼为尼尼为永尼和永尼.",
            },
            "ja": {
                "title": "アショートンコン",
                "description": "アショートンコンにいますだいないはバータートンコンです.",
            },
            "ko": {
                "title": "촌원세요 촌원세요",
                "description": "촌원세요안하세요 촌원세요안하세요 촌원세요안하세요 촌원세요안하세요.",
            },
            "vi": {
                "title": "Kébap Đển Đển",
                "description": "Miệa Đển đển ụa đển đển ụa đển đển.",
            },
        },
    },
    {
        "title": "Couscous Royale",
        "description": "Steamed couscous with seven vegetables and meats.",
        "cuisine": "moroccan", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("couscous-royale"),
        "tags": ["couscous", "stew", "banquet"],
        "ingredients": [
            {"name": "couscous"},
            {"name": "chicken"},
            {"name": "lamb"},
            {"name": "chickpeas"},
            {"name": "carrot"},
            {"name": "zucchini"},
            {"name": "ras el hanout"}
        ],
        "steps": [
            "Steam couscous twice.",
            "Braise meats with vegetables.",
            "Season with ras el hanout.",
            "Mound couscous.",
            "Ladle broth over."
        ],
        "translations": {
            "zh": {
                "title": "吃尼常常",
                "description": "游尼吃尼常、三个苹果和苹果.",
            },
            "ja": {
                "title": "コタカャーレー",
                "description": "気中吃コタカャーレー、三个苹果和苹果.",
            },
            "ko": {
                "title": "총주세요구세요",
                "description": "총주세요、三个苹果和苹果.",
            },
            "vi": {
                "title": "Couscous Vua",
                "description": "Couscous hấp với bảy loại rau và thịt.",
            },
        },
    },
    {
        "title": "Zaalouk",
        "description": "Smoky eggplant and tomato salad with cumin.",
        "cuisine": "moroccan", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("zaalouk"),
        "tags": ["salad", "vegetarian", "dip"],
        "ingredients": [
            {"name": "eggplant"},
            {"name": "tomatoes"},
            {"name": "garlic"},
            {"name": "cumin"},
            {"name": "paprika"},
            {"name": "olive oil"}
        ],
        "steps": [
            "Roast eggplant until collapsed.",
            "Cook tomatoes with garlic.",
            "Mash together.",
            "Season with spices.",
            "Serve warm or cold with bread."
        ],
        "translations": {
            "zh": {
                "title": "扎鲁克",
                "description": "烟熏茄子和西红柿沙拉，带有孜然香味",
            },
            "ja": {
                "title": "ザルーク",
                "description": "スモーキーなナスとトマトのサラダ、クミン風味",
            },
            "ko": {
                "title": "잘루크",
                "description": "연기향 나는 가지와 토마토 샐러드, 쿠민 맛",
            },
            "vi": {
                "title": "Salad cà tím Zaalouk",
                "description": "Salad cà tím và cà chua khói với hương cumin",
            },
        },
    },
    {
        "title": "Tibs",
        "description": "Sautéed beef or lamb with awaze sauce and rosemary.",
        "cuisine": "ethiopian", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("tibs"),
        "tags": ["stir-fry", "beef", "classic"],
        "ingredients": [
            {"name": "beef strips"},
            {"name": "awaze paste"},
            {"name": "rosemary"},
            {"name": "onion"},
            {"name": "butter"},
            {"name": "berbere"}
        ],
        "steps": [
            "Sear beef quickly.",
            "Sauté onion.",
            "Add awaze and butter.",
            "Finish with rosemary.",
            "Serve with injera."
        ],
        "translations": {
            "zh": {
                "title": "提布斯",
                "description": "用阿瓦兹酱和迷迭香炒牛肉或羊肉",
            },
            "ja": {
                "title": "ティブス",
                "description": "アワゼソースとローズマリーを用いた牛肉またはラムの炒め物",
            },
            "ko": {
                "title": "티브스",
                "description": "아와제 소스와迷迭香을 넣은 소고기 또는 양고기 볶음",
            },
            "vi": {
                "title": "Thịt bò Tibs Ethiopia",
                "description": "Thịt bò hoặc cừu xào với nước sốt awaze và hương thảo",
            },
        },
    },
    {
        "title": "Shiro Wat",
        "description": "Silky chickpea flour stew with berbere.",
        "cuisine": "ethiopian", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("shiro-wat"),
        "tags": ["stew", "vegetarian", "comfort"],
        "ingredients": [
            {"name": "shiro flour"},
            {"name": "berbere"},
            {"name": "onion"},
            {"name": "garlic"},
            {"name": "oil"},
            {"name": "stock"}
        ],
        "steps": [
            "Cook onion until soft.",
            "Stir in berbere.",
            "Whisk in shiro gradually.",
            "Simmer until thick.",
            "Serve on injera."
        ],
        "translations": {
            "zh": {
                "title": "什罗瓦特",
                "description": "丝滑的鹰嘴豆粉炖菜，加入伯伯雷香料",
            },
            "ja": {
                "title": "シロワット",
                "description": "なめらかなひよこ豆粉のシチューにベルベレを添えたエチオピア料理",
            },
            "ko": {
                "title": "시로와트",
                "description": "부드러운 鹰嘴豆 가루 스튜에 베르베레를 더한 에티오피아 요리",
            },
            "vi": {
                "title": "Hầm đậu tương Shiro",
                "description": "Món hầm bột đậu gà mịn với gia vị berbere",
            },
        },
    },
    {
        "title": "Kare-Kare",
        "description": "Oxtail stew in peanut sauce with bagoong.",
        "cuisine": "filipino", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("kare-kare"),
        "tags": ["stew", "oxtail", "classic"],
        "ingredients": [
            {"name": "oxtail"},
            {"name": "peanut butter"},
            {"name": "annatto"},
            {"name": "eggplant"},
            {"name": "bok choy"},
            {"name": "bagoong"}
        ],
        "steps": [
            "Simmer oxtail until tender.",
            "Make peanut-annatto sauce.",
            "Add vegetables.",
            "Simmer until glossy.",
            "Serve with bagoong on side."
        ],
        "translations": {
            "zh": {
                "title": "卡雷-卡雷",
                "description": "用花生酱和巴戈恩制作的牛尾汤",
            },
            "ja": {
                "title": "カレーカレー",
                "description": "バゴォンとピーナッツソースのオクタイルシチュー",
            },
            "ko": {
                "title": "카레카레",
                "description": "바고옹과 땅콩소스에煮된 소꼬리 스튜",
            },
            "vi": {
                "title": "Kare-kare thịt bò Philippines",
                "description": "Món hầm đuôi bò trong sốt lạc với bagoong",
            },
        },
    },
    {
        "title": "Pancit Canton",
        "description": "Stir-fried wheat noodles with soy and vegetables.",
        "cuisine": "filipino", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("pancit"),
        "tags": ["noodles", "stir-fry", "party"],
        "ingredients": [
            {"name": "canton noodles"},
            {"name": "soy sauce"},
            {"name": "cabbage"},
            {"name": "carrot"},
            {"name": "shrimp"},
            {"name": "pork"}
        ],
        "steps": [
            "Soak noodles.",
            "Stir-fry protein.",
            "Add vegetables.",
            "Toss noodles with soy.",
            "Garnish with calamansi."
        ],
        "translations": {
            "zh": {
                "title": "约尿尿尿",
                "description": "约尿尿约尿约尿约尿约尿约尿约尿",
            },
            "ja": {
                "title": "バーカトンター",
                "description": "バーカトンターにアイバトにバートンターを下だ",
            },
            "ko": {
                "title": "안사주엀구",
                "description": "안사주엀구 주세요 총세요 주세요",
            },
            "vi": {
                "title": "Bền xót đền",
                "description": "Bền xót đền đền ại đền",
            },
        },
    },
    {
        "title": "Seekh Kebab",
        "description": "Spiced minced lamb grilled on skewers.",
        "cuisine": "pakistani", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("seekh-kebab"),
        "tags": ["grill", "lamb", "classic"],
        "ingredients": [
            {"name": "ground lamb"},
            {"name": "ginger"},
            {"name": "garlic"},
            {"name": "garam masala"},
            {"name": "green chili"},
            {"name": "coriander"}
        ],
        "steps": [
            "Mix lamb with spices.",
            "Mold onto skewers.",
            "Grill over charcoal.",
            "Turn until cooked through.",
            "Serve with naan and chutney."
        ],
        "translations": {
            "zh": {
                "title": "王尽美尽",
                "description": "美尽美尽美尽美美美美美美美美美美美美美美美美美美",
            },
            "ja": {
                "title": "スェコカルンスン",
                "description": "スェコカルンスンスンスンスンスン",
            },
            "ko": {
                "title": "엃폸세요",
                "description": "엃폸세요 엃폸세요 엃폸세요 엃폸세요 엃폸세요",
            },
            "vi": {
                "title": "Đái Đái Đái",
                "description": "Đái Đái Đái Đái Đái Đái Đái Đái",
            },
        },
    },
    {
        "title": "Chapli Kebab",
        "description": "Flat Peshawari minced meat patties with pomegranate.",
        "cuisine": "pakistani", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("chapli-kebab"),
        "tags": ["grill", "beef", "street food"],
        "ingredients": [
            {"name": "ground beef"},
            {"name": "coriander seeds"},
            {"name": "pomegranate seeds"},
            {"name": "tomato"},
            {"name": "green chili"}
        ],
        "steps": [
            "Mix beef with spices and seeds.",
            "Form flat patties.",
            "Pan-fry or grill.",
            "Serve with raita.",
            "Eat with naan."
        ],
        "translations": {
            "zh": {
                "title": "恰普利烤肉饼",
                "description": "平坦的白沙瓦风格的碎肉饼配以石榴",
            },
            "ja": {
                "title": "チャプリカバブ",
                "description": "ペシャワール風のミンチ肉のパティにグレープフルーツ",
            },
            "ko": {
                "title": "차플리 카밥",
                "description": "펫사와리 양식의 얇은 다진 고기 패티에 석류",
            },
            "vi": {
                "title": "Kebab Chapli Pakistan",
                "description": "Bánh thịt heo Peshawari mỏng với quả lựu",
            },
        },
    },
    {
        "title": "Kottu Roti",
        "description": "Chopped godamba roti stir-fried on a griddle.",
        "cuisine": "sri_lankan", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("kottu-roti"),
        "tags": ["stir-fry", "street food", "spicy"],
        "ingredients": [
            {"name": "godamba roti"},
            {"name": "egg"},
            {"name": "chicken"},
            {"name": "carrot"},
            {"name": "leeks"},
            {"name": "curry spices"}
        ],
        "steps": [
            "Chop roti on hot griddle.",
            "Add vegetables and meat.",
            "Toss with spices.",
            "Crack egg into mix.",
            "Serve with gravy on side."
        ],
        "translations": {
            "zh": {
                "title": "科图罗提",
                "description": "将戈丹巴罗提切成小块，在铁板上炒制。",
            },
            "ja": {
                "title": "コッテュ・ロティ",
                "description": "ゴダンバ・ロティを刻んで鉄板で炒める。",
            },
            "ko": {
                "title": "코투로티",
                "description": "고단바 로티를 잘라서 프라이팬에서 볶아 만든 음식입니다.",
            },
            "vi": {
                "title": "Bánh roti xào Sri Lanka",
                "description": "Cắt nhỏ bánh mì godamba roti và xào trên chảo",
            },
        },
    },
    {
        "title": "Fish Ambul Thiyal",
        "description": "Sour black pepper fish curry from the south.",
        "cuisine": "sri_lankan", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("fish-ambul-thiyal"),
        "tags": ["curry", "fish", "classic"],
        "ingredients": [
            {"name": "tuna steaks"},
            {"name": "goraka"},
            {"name": "black pepper"},
            {"name": "curry leaves"},
            {"name": "coconut"}
        ],
        "steps": [
            "Toast pepper and goraka.",
            "Simmer fish in spiced coconut.",
            "Reduce until dry and sour.",
            "Rest flavors.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "經港帽强尽强",
                "description": "気尽强尽强测译之一四的尽强尽强",
            },
            "ja": {
                "title": "フイシメストインス",
                "description": "尽强测译、测译之一四的尽强测译",
            },
            "ko": {
                "title": "구가帽强尽强",
                "description": "尽强测译、测译之丁四的尽强测译",
            },
            "vi": {
                "title": "ỉạỏề ảằụểỉ",
                "description": "ảằụểỉỉụỉ ỉạỏề、ỉạỏề之丁四的ỉạỏề测译",
            },
        },
    },
    {
        "title": "Fish Amok",
        "description": "Steamed fish custard in banana leaf cups.",
        "cuisine": "cambodian", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("fish-amok"),
        "tags": ["steamed", "fish", "classic"],
        "ingredients": [
            {"name": "white fish"},
            {"name": "kroeung paste"},
            {"name": "coconut milk"},
            {"name": "egg"},
            {"name": "banana leaves"}
        ],
        "steps": [
            "Blend kroeung with coconut.",
            "Fold in fish.",
            "Steam in leaf cups 20 min.",
            "Garnish with coconut cream.",
            "Serve warm."
        ],
        "translations": {
            "zh": {
                "title": "筸字安强",
                "description": "平安筸安强尼尼常强圣一个安强帽常强尼尼常强圣一个安强帽常强",
            },
            "ja": {
                "title": "フィルメン",
                "description": "强强フィルメントージェアコーター",
            },
            "ko": {
                "title": "구가安强",
                "description": "平安구가安强尼尼常强圣一个安强帽常强尼尼常强",
            },
            "vi": {
                "title": "ỉ᭽ợẽỡ",
                "description": "ỉ᭽ợẽỡụẹừẽỡụẹừẽỡụẹừẽỡ",
            },
        },
    },
    {
        "title": "Beef Lok Lak",
        "description": "Stir-fried beef with lime-pepper dipping sauce.",
        "cuisine": "cambodian", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("lok-lak"),
        "tags": ["stir-fry", "beef", "classic"],
        "ingredients": [
            {"name": "beef strips"},
            {"name": "oyster sauce"},
            {"name": "tomato"},
            {"name": "lettuce"},
            {"name": "lime pepper dip"}
        ],
        "steps": [
            "Marinate and sear beef.",
            "Stir-fry with tomato.",
            "Make lime-pepper dip.",
            "Serve on lettuce cups.",
            "Eat with rice."
        ],
        "translations": {
            "zh": {
                "title": "王小统计",
                "description": "影常小统计、约强索汘测警",
            },
            "ja": {
                "title": "バールレール",
                "description": "トェコントショナ、索汘バーストショナ",
            },
            "ko": {
                "title": "가가가가구 구가가가",
                "description": "가가가가가구 가가가가가가가가가가",
            },
            "vi": {
                "title": "ỉ᯺ụẽợẽụừẽịụợế",
                "description": "ỉ᯺ụẽợẽụừẽịụợếụếụẽụẽị",
            },
        },
    },
    {
        "title": "Feijoada",
        "description": "Black bean stew with smoked pork and sausage.",
        "cuisine": "brazilian", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("feijoada"),
        "tags": ["stew", "pork", "classic"],
        "ingredients": [
            {"name": "black beans"},
            {"name": "pork ribs"},
            {"name": "linguiça"},
            {"name": "bay leaves"},
            {"name": "orange"},
            {"name": "collard greens"}
        ],
        "steps": [
            "Soak beans overnight.",
            "Simmer with meats 3 hours.",
            "Skim and season.",
            "Serve with rice and greens.",
            "Garnish with orange."
        ],
        "translations": {
            "zh": {
                "title": "菲若达",
                "description": "黑豆炖烟熏猪肉和香肠",
            },
            "ja": {
                "title": "フィジョアーダ",
                "description": "黒豆と煙熏豚肉、ソーセージのシチュー",
            },
            "ko": {
                "title": "페이조아다",
                "description": "흰콩과 훈제돼지고기, 소시지의 스튜",
            },
            "vi": {
                "title": "Món đậu đen Brazil",
                "description": "Món hầm đậu đen với thịt lợn hun khói và xúc xích",
            },
        },
    },
    {
        "title": "Pão de Queijo",
        "description": "Chewy cheese bread made with tapioca flour.",
        "cuisine": "brazilian", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("pao-de-queijo"),
        "tags": ["bread", "cheese", "snack"],
        "ingredients": [
            {"name": "tapioca flour"},
            {"name": "cheese"},
            {"name": "eggs"},
            {"name": "milk"},
            {"name": "oil"},
            {"name": "salt"}
        ],
        "steps": [
            "Heat milk and oil.",
            "Mix into tapioca flour.",
            "Add cheese and eggs.",
            "Roll into balls.",
            "Bake until puffed."
        ],
        "translations": {
            "zh": {
                "title": "巴西酥饼",
                "description": "用淀粉粉做成的软酥奶酪面包",
            },
            "ja": {
                "title": "バイスディル",
                "description": "ディコンバートスンになしたバーストスンバースンにバーストスンバースント",
            },
            "ko": {
                "title": "총어재이시",
                "description": "총어재이시 문재이시 었세요",
            },
            "vi": {
                "title": "Bánh Bông Lan",
                "description": "Bánh làm từ bột tapioca mềm và ngon",
            },
        },
    },
    {
        "title": "Lomo Saltado",
        "description": "Stir-fried beef with fries, soy, and ají amarillo.",
        "cuisine": "peruvian", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("lomo-saltado"),
        "tags": ["stir-fry", "beef", "fusion"],
        "ingredients": [
            {"name": "beef strips"},
            {"name": "fries"},
            {"name": "onion"},
            {"name": "tomato"},
            {"name": "soy sauce"},
            {"name": "ají amarillo"}
        ],
        "steps": [
            "Sear beef over high heat.",
            "Add onion and tomato.",
            "Toss with soy and ají.",
            "Fold in crispy fries.",
            "Serve with rice."
        ],
        "translations": {
            "zh": {
                "title": "洛莫萨尔塔多",
                "description": "炒牛肉配薯条、酱油和黄辣椒",
            },
            "ja": {
                "title": "ロモサルタード",
                "description": "牛肉とフライを炒めたペルー風料理に醤油とアヒアマリロを添える",
            },
            "ko": {
                "title": "로모 살타도",
                "description": "소고기와 감자튀김, 간장, 그리고 아히 아마릴로를 넣은 페루식 볶음 요리",
            },
            "vi": {
                "title": "Thịt bò xào kiểu Peru",
                "description": "Thịt bò xào với khoai tây chiên, nước tương và ớt vàng",
            },
        },
    },
    {
        "title": "Aji de Gallina",
        "description": "Creamy shredded chicken in walnut-aji sauce.",
        "cuisine": "peruvian", "language": "en", "spice_level": 1,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("aji-de-gallina"),
        "tags": ["chicken", "comfort", "classic"],
        "ingredients": [
            {"name": "shredded chicken"},
            {"name": "ají amarillo"},
            {"name": "walnuts"},
            {"name": "evaporated milk"},
            {"name": "bread"},
            {"name": "parmesan"}
        ],
        "steps": [
            "Blend ají sauce with walnuts.",
            "Simmer with chicken.",
            "Thicken with bread.",
            "Serve over rice.",
            "Garnish with olives and egg."
        ],
        "translations": {
            "zh": {
                "title": "阿吉德加利娜",
                "description": "奶油鸡肉沾 Walnut-阿吉酱",
            },
            "ja": {
                "title": "アジ・デ・ガリーナ",
                "description": "ナッツとアジソースが合わさったクリーミーな鶏肉",
            },
            "ko": {
                "title": "아지 데 갈리나",
                "description": "호두 아지 소스에 담근 크림 치킨",
            },
            "vi": {
                "title": "Gà sốt ớt vàng Peru",
                "description": "Thịt gà xé tơi sốt walnut-aji kem",
            },
        },
    },
    {
        "title": "Jerk Chicken",
        "description": "Scotch bonnet-marinated grilled chicken.",
        "cuisine": "caribbean", "language": "en", "spice_level": 3,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("jerk-chicken"),
        "tags": ["grill", "chicken", "classic"],
        "ingredients": [
            {"name": "chicken"},
            {"name": "scotch bonnet"},
            {"name": "allspice"},
            {"name": "thyme"},
            {"name": "scallion"},
            {"name": "soy"}
        ],
        "steps": [
            "Blend jerk marinade.",
            "Marinate chicken overnight.",
            "Grill over pimento wood if possible.",
            "Char and rest.",
            "Serve with festival or rice."
        ],
        "translations": {
            "zh": {
                "title": "椰子鸡",
                "description": "用西班牙辣椒酱浸泡的烤鸡",
            },
            "ja": {
                "title": "ジャーキーチキン",
                "description": "スコッチボンネットマリネのグリルチキン",
            },
            "ko": {
                "title": "제릭 치킨",
                "description": "스콧 보네타 마리네드 그릴 치킨",
            },
            "vi": {
                "title": "Gà Jerk",
                "description": "Gà nướng được ướp với hỗn hợp gia vị Scotch bonnet",
            },
        },
    },
    {
        "title": "Rice and Peas",
        "description": "Coconut rice with kidney beans and thyme.",
        "cuisine": "caribbean", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("rice-and-peas"),
        "tags": ["rice", "side", "comfort"],
        "ingredients": [
            {"name": "jasmine rice"},
            {"name": "kidney beans"},
            {"name": "coconut milk"},
            {"name": "thyme"},
            {"name": "scallion"},
            {"name": "garlic"}
        ],
        "steps": [
            "Sauté garlic and thyme.",
            "Add rice, beans, coconut milk.",
            "Simmer until fluffy.",
            "Rest covered.",
            "Fluff with scallion."
        ],
        "translations": {
            "zh": {
                "title": "王美和米尺",
                "description": "美美和米尺了汿安米和例武尺",
            },
            "ja": {
                "title": "トィターバーバー",
                "description": "トィターバーバーにいないはパーターバーバーにいないは",
            },
            "ko": {
                "title": "구고기가가가구",
                "description": "촜우세요 촜우세요 번세요 촜우세요 번세요",
            },
            "vi": {
                "title": "ảộạộấẹẽịềẹể",
                "description": "ảộạộấẹẽịềẹểợẹềểợẹềểụẽịềẹể",
            },
        },
    },
    {
        "title": "Taiwanese Beef Noodle Soup",
        "description": "Braised beef shank in spiced soy broth with noodles.",
        "cuisine": "taiwanese", "language": "en", "spice_level": 2,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("beef-noodle-soup"),
        "tags": ["noodles", "soup", "classic"],
        "ingredients": [
            {"name": "beef shank"},
            {"name": "soy sauce"},
            {"name": "star anise"},
            {"name": "tomato"},
            {"name": "wheat noodles"},
            {"name": "bok choy"}
        ],
        "steps": [
            "Braise beef 2 hours in spiced soy.",
            "Cook noodles.",
            "Blanch greens.",
            "Assemble bowls.",
            "Top with pickled mustard."
        ],
        "translations": {
            "zh": {
                "title": "约五尿强尿尿尿",
                "description": "约五尿强尿尿尿一个强尿尿尿尿尿一个强尿尿尿尿尿尿",
            },
            "ja": {
                "title": "トメサインバーサント",
                "description": "トメサインバーサントに尿尿できういにきたいだ",
            },
            "ko": {
                "title": "구가기가개가가가가",
                "description": "구가기가개가가가가가가가가가가가",
            },
            "vi": {
                "title": "Máậạộảẹịốụẽềụ",
                "description": "Máậạộảẹịốụẽềụẽềụẽềụẽềụ",
            },
        },
    },
    {
        "title": "Lu Rou Fan",
        "description": "Braised minced pork over rice with pickled veg.",
        "cuisine": "taiwanese", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("lu-rou-fan"),
        "tags": ["rice", "pork", "comfort"],
        "ingredients": [
            {"name": "ground pork"},
            {"name": "soy sauce"},
            {"name": "rock sugar"},
            {"name": "five-spice"},
            {"name": "rice"},
            {"name": "pickled cucumber"}
        ],
        "steps": [
            "Brown pork.",
            "Braise with soy and sugar.",
            "Reduce to thick sauce.",
            "Serve over rice.",
            "Add pickles on side."
        ],
        "translations": {
            "zh": {
                "title": "王美尼",
                "description": "美美美尼尼尼尼尼尼尼尼尼尼尼尼",
            },
            "ja": {
                "title": "メャンムウスイン",
                "description": "メャンムウスインはバーコントにいるバーコントを下だた",
            },
            "ko": {
                "title": "주주안세요",
                "description": "주주안세요하세요 주주안세요 총세요 주주안세요 총가세요",
            },
            "vi": {
                "title": "ệ đầ ồ để đợ",
                "description": "ệ đầ ồ để đợ đổ để đợ đệ đợ để đợ",
            },
        },
    },
    {
        "title": "Bacalhau à Brás",
        "description": "Shredded salt cod with eggs and matchstick potatoes.",
        "cuisine": "portuguese", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("bacalhau-bras"),
        "tags": ["fish", "eggs", "classic"],
        "ingredients": [
            {"name": "salt cod"},
            {"name": "potatoes"},
            {"name": "eggs"},
            {"name": "onion"},
            {"name": "olives"},
            {"name": "parsley"}
        ],
        "steps": [
            "Soak and shred cod.",
            "Fry potato matchsticks.",
            "Sauté onion and cod.",
            "Scramble in eggs.",
            "Garnish with olives."
        ],
        "translations": {
            "zh": {
                "title": "巴卡洛阿布拉斯",
                "description": "用鸡蛋和细条土豆拌碎的咸鳕鱼",
            },
            "ja": {
                "title": "バカラウ・ア・ブラス",
                "description": "塩鮭を細かく刻んで卵と細切りのジャガイモと合わせて",
            },
            "ko": {
                "title": "바칼라우 아 브라스",
                "description": "소금에 절인 대구를 으깨서 계란과 썬감자와 함께",
            },
            "vi": {
                "title": "Cá tuyết xào trứng khoai tây",
                "description": "Cá tuyết muối xé nhỏ với trứng và khoai tây cắt que",
            },
        },
    },
    {
        "title": "Caldo Verde",
        "description": "Kale and potato soup with chouriço.",
        "cuisine": "portuguese", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("caldo-verde"),
        "tags": ["soup", "comfort", "classic"],
        "ingredients": [
            {"name": "potatoes"},
            {"name": "kale"},
            {"name": "chouriço"},
            {"name": "onion"},
            {"name": "olive oil"},
            {"name": "stock"}
        ],
        "steps": [
            "Simmer potatoes in stock.",
            "Blend partially.",
            "Add thinly sliced kale.",
            "Slice and fry chouriço.",
            "Serve with olive oil drizzle."
        ],
        "translations": {
            "zh": {
                "title": "卡尔多维尔德",
                "description": "菠菜和土豆汤配上香肠",
            },
            "ja": {
                "title": "カルド・ヴェルデ",
                "description": "ケールとジャガイモのスープにチョリソー",
            },
            "ko": {
                "title": "칼도 베르데",
                "description": "케일과 감자 수프에 초리소",
            },
            "vi": {
                "title": "Caldo Verde",
                "description": "Súp cải kale và khoai tây với xúc xích",
            },
        },
    },
    {
        "title": "Fish and Chips",
        "description": "Beer-battered cod with thick-cut fries.",
        "cuisine": "british", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("fish-and-chips"),
        "tags": ["fried", "fish", "classic"],
        "ingredients": [
            {"name": "cod fillets"},
            {"name": "flour"},
            {"name": "beer batter"},
            {"name": "potatoes"},
            {"name": "malt vinegar"},
            {"name": "oil"}
        ],
        "steps": [
            "Cut and soak chips.",
            "Make light beer batter.",
            "Fry fish until crisp.",
            "Fry chips golden.",
            "Serve with vinegar."
        ],
        "translations": {
            "zh": {
                "title": "美子和美尼",
                "description": "漏子尼三尼给一中平尼",
            },
            "ja": {
                "title": "フィシャックト",
                "description": "ドクトプローチイントーショナ",
            },
            "ko": {
                "title": "촜식이우세요었세요",
                "description": "촜식이우세요 었세요 촜식이우세요 었세요",
            },
            "vi": {
                "title": "ệt Ìt Ìp Ìt Ìp",
                "description": "đị Ìt Ìp Ìt Ìp ạ Ìt Ìp Ìt Ìp",
            },
        },
    },
    {
        "title": "Shepherd's Pie",
        "description": "Lamb mince topped with buttery mashed potato.",
        "cuisine": "british", "language": "en", "spice_level": 0,
        "prep": 15, "cook": 30, "servings": 4, "image": _img("shepherds-pie"),
        "tags": ["baked", "lamb", "comfort"],
        "ingredients": [
            {"name": "ground lamb"},
            {"name": "onion"},
            {"name": "carrot"},
            {"name": "peas"},
            {"name": "mashed potato"},
            {"name": "Worcestershire"}
        ],
        "steps": [
            "Brown lamb with vegetables.",
            "Simmer with Worcestershire.",
            "Top with mashed potato.",
            "Fork ridges on top.",
            "Bake until golden."
        ],
        "translations": {
            "zh": {
                "title": "王纳置",
                "description": "置纳置名尼为置纳置为置纳置一为置纳置置置置置置置置置",
            },
            "ja": {
                "title": "シーベーター",
                "description": "シーベーターはパットパックターだ。",
            },
            "ko": {
                "title": "이호원린",
                "description": "이호원린세요 이호원린세요 이호원린세요",
            },
            "vi": {
                "title": "ỉ᯺ụếợỏụế",
                "description": "ỉ᯺ụếợỏụếợỏụếợỏụế",
            },
        },
    },
]
