"""Generate 2 additional iconic recipes per original (pre-v5) cuisine.

Run: uv run python -m scripts.generate_original_expansion
Writes: scripts/cuisine_expansion_v6_original.py
"""

from __future__ import annotations

from pathlib import Path

# (wire, slug, title, description, spice, tags, ingredients, steps)
_DISHES: list[tuple] = [
    ("korean", "bulgogi", "Bulgogi", "Sweet soy-marinated grilled beef, Korea's barbecue classic.", 1,
     ["grill", "beef", "classic"],
     ["600 g ribeye, sliced thin", "soy sauce", "pear puree", "garlic", "sesame oil", "scallion"],
     ["Marinate beef 2 hours.", "Grill over high heat in batches.", "Garnish with scallion and sesame.", "Serve with rice and lettuce wraps.", "Eat immediately."]),
    ("korean", "sundubu-jjigae", "Sundubu Jjigae", "Spicy soft tofu stew with seafood or pork.", 2,
     ["stew", "tofu", "comfort"],
     ["soft tofu", "kimchi", "gochugaru", "clams or pork", "egg", "stock"],
     ["Sauté kimchi and chili paste.", "Add stock and simmer.", "Slide in tofu gently.", "Add protein; poach egg on top.", "Serve bubbling in earthenware pot."]),
    ("japanese", "tonkatsu", "Tonkatsu", "Panko-crusted pork cutlet with tangy sauce.", 0,
     ["fried", "pork", "classic"],
     ["pork loin", "panko", "flour", "egg", "tonkatsu sauce", "shredded cabbage"],
     ["Pound cutlets even.", "Bread with flour, egg, panko.", "Deep-fry until golden.", "Rest and slice.", "Serve with sauce and cabbage."]),
    ("japanese", "chicken-teriyaki", "Chicken Teriyaki", "Glossy soy-mirin glazed chicken over rice.", 0,
     ["chicken", "glaze", "weeknight"],
     ["chicken thighs", "soy sauce", "mirin", "sake", "sugar", "ginger"],
     ["Sear chicken skin-side down.", "Simmer with teriyaki sauce.", "Reduce until lacquered.", "Slice and serve over rice.", "Garnish with sesame."]),
    ("chinese", "general-tsos-chicken", "General Tso's Chicken", "Crispy fried chicken in sweet-spicy glaze.", 2,
     ["fried", "chicken", "classic"],
     ["chicken thigh", "soy sauce", "rice vinegar", "sugar", "dried chilies", "cornstarch"],
     ["Fry battered chicken crisp.", "Stir-fry dried chilies.", "Toss with sweet-spicy sauce.", "Garnish with scallion.", "Serve with rice."]),
    ("chinese", "chow-mein", "Chow Mein", "Wok-tossed noodles with vegetables and protein.", 0,
     ["noodles", "stir-fry", "weeknight"],
     ["egg noodles", "cabbage", "carrot", "bean sprouts", "soy sauce", "sesame oil"],
     ["Boil noodles; drain.", "Stir-fry vegetables.", "Toss noodles with soy and oil.", "Add protein if using.", "Serve hot from wok."]),
    ("burmese", "ohn-no-khao-swe", "Ohn No Khao Swè", "Coconut chicken noodle soup with crispy toppings.", 1,
     ["noodles", "soup", "comfort"],
     ["wheat noodles", "coconut milk", "chicken", "onion", "chickpea fritters", "hard-boiled egg"],
     ["Simmer chicken in aromatics.", "Add coconut milk.", "Cook noodles separately.", "Assemble bowls with toppings.", "Serve with lime and chili."]),
    ("burmese", "burmese-curry", "Burmese Chicken Curry", "Turmeric-rich curry with fragrant curry powder.", 1,
     ["curry", "chicken", "comfort"],
     ["chicken pieces", "onion", "garlic", "ginger", "turmeric", "Burmese curry powder"],
     ["Bloom spices in oil.", "Brown chicken.", "Simmer with water 35 min.", "Reduce to thick gravy.", "Serve with rice."]),
    ("thai", "massaman-curry", "Massaman Curry", "Mild peanut coconut curry with potatoes and beef.", 1,
     ["curry", "beef", "comfort"],
     ["beef chuck", "massaman paste", "coconut milk", "potato", "peanuts", "tamarind"],
     ["Brown beef.", "Fry curry paste in coconut cream.", "Simmer with potato until tender.", "Finish with peanuts and tamarind.", "Serve with jasmine rice."]),
    ("thai", "pad-thai", "Pad Thai", "Tamarind rice noodles with shrimp, tofu, and peanuts.", 1,
     ["noodles", "stir-fry", "classic"],
     ["rice noodles", "shrimp", "tofu", "tamarind paste", "fish sauce", "peanuts", "bean sprouts"],
     ["Soak noodles.", "Stir-fry protein.", "Toss noodles with sauce.", "Add sprouts and peanuts.", "Serve with lime."]),
    ("vietnamese", "bun-cha", "Bun Cha", "Grilled pork patties with vermicelli and herbs.", 1,
     ["noodles", "grill", "classic"],
     ["ground pork", "fish sauce", "rice vermicelli", "herbs", "nuoc cham", "pickled veg"],
     ["Form and grill pork patties.", "Make dipping sauce.", "Cook vermicelli.", "Arrange herbs and noodles.", "Dip and assemble at table."]),
    ("vietnamese", "com-tam", "Com Tam", "Broken rice plate with grilled pork chop and egg.", 0,
     ["rice", "grill", "street food"],
     ["broken rice", "pork chop", "egg", "pickled daikon", "nuoc cham", "scallion oil"],
     ["Grill marinated pork chop.", "Fry egg sunny-side up.", "Steam broken rice.", "Plate with pickles and oil.", "Serve with fish sauce."]),
    ("indian", "butter-chicken", "Butter Chicken", "Creamy tomato curry with tandoori-spiced chicken.", 1,
     ["curry", "chicken", "classic"],
     ["chicken", "tomato puree", "butter", "cream", "garam masala", "kasuri methi"],
     ["Char chicken in tandoor or grill.", "Simmer tomato-butter sauce.", "Add cream and spices.", "Simmer chicken in sauce.", "Serve with naan."]),
    ("indian", "samosas", "Vegetable Samosas", "Crisp pastry triangles with spiced potato filling.", 1,
     ["fried", "snack", "vegetarian"],
     ["potatoes", "peas", "cumin", "samosa wrappers", "oil", "coriander"],
     ["Cook spiced potato-pea filling.", "Fill and fold samosas.", "Seal edges.", "Deep-fry until golden.", "Serve with chutney."]),
    ("italian", "lasagna", "Lasagna Bolognese", "Layered pasta with rich meat ragù and béchamel.", 0,
     ["pasta", "baked", "comfort"],
     ["lasagna sheets", "beef ragù", "béchamel", "parmesan", "mozzarella"],
     ["Make ragù low and slow.", "Layer pasta, ragù, béchamel.", "Repeat; top with cheese.", "Bake until bubbling.", "Rest 10 min before cutting."]),
    ("italian", "risotto-milanese", "Risotto alla Milanese", "Saffron risotto finished with butter and parmesan.", 0,
     ["rice", "risotto", "classic"],
     ["arborio rice", "saffron", "white wine", "parmesan", "butter", "stock"],
     ["Toast rice in butter.", "Deglaze with wine.", "Add stock ladle by ladle.", "Finish with saffron, butter, cheese.", "Serve immediately."]),
    ("american_western", "mac-and-cheese", "Mac and Cheese", "Creamy cheddar sauce tossed with elbow pasta.", 0,
     ["pasta", "comfort", "classic"],
     ["elbow pasta", "cheddar", "milk", "butter", "flour", "breadcrumbs"],
     ["Cook pasta al dente.", "Make roux-based cheese sauce.", "Toss pasta with sauce.", "Top with breadcrumbs.", "Bake until golden."]),
    ("american_western", "bbq-ribs", "BBQ Baby Back Ribs", "Low-and-slow ribs with sticky barbecue glaze.", 1,
     ["ribs", "grill", "weekend"],
     ["baby back ribs", "dry rub", "barbecue sauce", "apple cider vinegar", "brown sugar"],
     ["Rub ribs; rest overnight.", "Smoke or bake low 3 hours.", "Glaze with BBQ sauce.", "Finish over high heat.", "Rest and slice."]),
    ("mexican", "enchiladas", "Chicken Enchiladas", "Rolled tortillas baked in red chili sauce.", 2,
     ["baked", "chicken", "comfort"],
     ["corn tortillas", "shredded chicken", "enchilada sauce", "cheese", "onion", "crema"],
     ["Warm tortillas.", "Fill with chicken and onion.", "Roll and place in baking dish.", "Cover with sauce and cheese.", "Bake until bubbly."]),
    ("mexican", "pozole", "Pozole Rojo", "Hominy stew with pork and dried chilies.", 2,
     ["soup", "pork", "classic"],
     ["pork shoulder", "hominy", "dried guajillo chilies", "oregano", "radish", "lime"],
     ["Simmer pork until tender.", "Blend chili sauce.", "Add hominy and pork.", "Simmer 30 min.", "Serve with radish and lime."]),
    ("french", "boeuf-bourguignon", "Boeuf Bourguignon", "Beef braised in red wine with mushrooms.", 0,
     ["braised", "beef", "classic"],
     ["beef chuck", "red wine", "bacon", "pearl onions", "mushrooms", "thyme"],
     ["Sear beef; set aside.", "Cook bacon and vegetables.", "Deglaze with wine.", "Braise 3 hours.", "Add mushrooms; serve."]),
    ("french", "croque-monsieur", "Croque Monsieur", "Ham and gruyère sandwich baked with béchamel.", 0,
     ["sandwich", "baked", "lunch"],
     ["bread", "ham", "gruyère", "béchamel", "butter", "nutmeg"],
     ["Layer ham and cheese on bread.", "Top with béchamel and more cheese.", "Bake until golden.", "Broil briefly.", "Serve hot."]),
    ("greek", "moussaka", "Moussaka", "Layered eggplant, spiced lamb, and béchamel bake.", 0,
     ["baked", "lamb", "classic"],
     ["eggplant", "ground lamb", "tomato", "béchamel", "cinnamon", "parmesan"],
     ["Roast eggplant slices.", "Cook lamb with tomato and spices.", "Layer eggplant and lamb.", "Top with béchamel.", "Bake until set."]),
    ("greek", "souvlaki", "Chicken Souvlaki", "Marinated grilled skewers with tzatziki.", 0,
     ["grill", "chicken", "street food"],
     ["chicken thigh", "lemon", "oregano", "garlic", "yogurt", "pita"],
     ["Marinate chicken overnight.", "Skewer and grill.", "Make tzatziki.", "Warm pita.", "Serve with salad and sauce."]),
    ("spanish", "paella", "Paella Valenciana", "Saffron rice with chicken, rabbit, and snails.", 0,
     ["rice", "seafood", "classic"],
     ["bomba rice", "chicken", "rabbit optional", "saffron", "green beans", "stock"],
     ["Brown meats in paella pan.", "Add rice and saffron stock.", "Do not stir after this point.", "Cook until socarrat forms.", "Rest 5 min before serving."]),
    ("spanish", "patatas-bravas", "Patatas Bravas", "Crispy potatoes with smoky paprika sauce.", 1,
     ["tapas", "potato", "snack"],
     ["potatoes", "smoked paprika", "tomato", "garlic", "aioli", "oil"],
     ["Parboil and fry potatoes crisp.", "Simmer bravas sauce.", "Make garlic aioli.", "Toss potatoes in sauce.", "Drizzle aioli."]),
    ("malaysian", "nasi-lemak", "Nasi Lemak", "Coconut rice with sambal, anchovies, and egg.", 2,
     ["rice", "breakfast", "classic"],
     ["coconut rice", "sambal", "fried anchovies", "peanuts", "cucumber", "egg"],
     ["Cook rice in coconut milk.", "Fry ikan bilis crisp.", "Make sambal.", "Boil or fry egg.", "Plate all components."]),
    ("malaysian", "laksa", "Curry Laksa", "Spicy coconut noodle soup with tofu and prawns.", 2,
     ["noodles", "soup", "spicy"],
     ["rice noodles", "laksa paste", "coconut milk", "prawns", "tofu puffs", "bean sprouts"],
     ["Fry laksa paste.", "Add coconut milk and stock.", "Cook noodles.", "Assemble with toppings.", "Serve with lime."]),
    ("german", "wiener-schnitzel", "Wiener Schnitzel", "Thin breaded veal cutlet fried until golden.", 0,
     ["fried", "veal", "classic"],
     ["veal cutlets", "flour", "egg", "breadcrumbs", "lemon", "butter"],
     ["Pound cutlets thin.", "Bread sequentially.", "Fry in clarified butter.", "Drain on rack.", "Serve with lemon."]),
    ("german", "sauerkraut-pork", "Sauerkraut with Pork", "Slow-braised pork shoulder with tangy sauerkraut.", 0,
     ["braised", "pork", "comfort"],
     ["pork shoulder", "sauerkraut", "apple", "caraway", "onion", "stock"],
     ["Brown pork.", "Add sauerkraut, apple, caraway.", "Braise 2 hours.", "Shred pork if desired.", "Serve with potatoes."]),
    ("indonesian", "nasi-goreng", "Nasi Goreng", "Indonesian fried rice with kecap manis and egg.", 1,
     ["rice", "fried", "classic"],
     ["day-old rice", "kecap manis", "shallot", "garlic", "chili", "fried egg"],
     ["Stir-fry aromatics.", "Add rice and kecap.", "Toss over high heat.", "Top with fried egg.", "Serve with krupuk."]),
    ("indonesian", "rendang", "Beef Rendang", "Dry coconut curry slow-cooked until deeply caramelized.", 3,
     ["curry", "beef", "classic"],
     ["beef chuck", "coconut milk", "galangal", "lemongrass", "chilies", "kerisik"],
     ["Simmer beef in spiced coconut milk.", "Reduce slowly 3–4 hours.", "Toast coconut kerisik.", "Stir in until dry and dark.", "Rest before serving."]),
    ("lebanese", "fattoush", "Fattoush", "Crunchy salad with sumac dressing and fried pita.", 0,
     ["salad", "vegetarian", "fresh"],
     ["romaine", "tomato", "cucumber", "sumac", "fried pita", "pomegranate molasses"],
     ["Chop vegetables.", "Toast or fry pita chips.", "Whisk sumac dressing.", "Toss salad.", "Top with pita at last moment."]),
    ("lebanese", "shawarma", "Chicken Shawarma", "Spiced rotisserie chicken wrapped in flatbread.", 1,
     ["wrap", "chicken", "street food"],
     ["chicken thighs", "shawarma spice", "garlic sauce", "flatbread", "pickles", "tomato"],
     ["Marinate chicken with spices.", "Roast or grill until charred.", "Slice thin.", "Warm bread.", "Wrap with sauce and pickles."]),
    ("turkish", "menemen", "Menemen", "Soft scrambled eggs with tomatoes and peppers.", 1,
     ["eggs", "breakfast", "comfort"],
     ["eggs", "tomatoes", "green pepper", "onion", "olive oil", "pul biber"],
     ["Sauté pepper and onion.", "Add tomatoes; cook down.", "Pour in beaten eggs.", "Stir gently until just set.", "Serve in skillet with bread."]),
    ("turkish", "iskender-kebab", "Iskender Kebab", "Doner slices over pide with tomato sauce and butter.", 1,
     ["kebab", "lamb", "classic"],
     ["doner lamb", "pide bread", "tomato sauce", "yogurt", "butter", "sumac"],
     ["Warm pide cubes.", "Layer doner on top.", "Spoon hot tomato sauce.", "Add yogurt.", "Sizzle butter with paprika; pour over."]),
    ("moroccan", "couscous-royale", "Couscous Royale", "Steamed couscous with seven vegetables and meats.", 1,
     ["couscous", "stew", "banquet"],
     ["couscous", "chicken", "lamb", "chickpeas", "carrot", "zucchini", "ras el hanout"],
     ["Steam couscous twice.", "Braise meats with vegetables.", "Season with ras el hanout.", "Mound couscous.", "Ladle broth over."]),
    ("moroccan", "zaalouk", "Zaalouk", "Smoky eggplant and tomato salad with cumin.", 1,
     ["salad", "vegetarian", "dip"],
     ["eggplant", "tomatoes", "garlic", "cumin", "paprika", "olive oil"],
     ["Roast eggplant until collapsed.", "Cook tomatoes with garlic.", "Mash together.", "Season with spices.", "Serve warm or cold with bread."]),
    ("ethiopian", "tibs", "Tibs", "Sautéed beef or lamb with awaze sauce and rosemary.", 2,
     ["stir-fry", "beef", "classic"],
     ["beef strips", "awaze paste", "rosemary", "onion", "butter", "berbere"],
     ["Sear beef quickly.", "Sauté onion.", "Add awaze and butter.", "Finish with rosemary.", "Serve with injera."]),
    ("ethiopian", "shiro-wat", "Shiro Wat", "Silky chickpea flour stew with berbere.", 2,
     ["stew", "vegetarian", "comfort"],
     ["shiro flour", "berbere", "onion", "garlic", "oil", "stock"],
     ["Cook onion until soft.", "Stir in berbere.", "Whisk in shiro gradually.", "Simmer until thick.", "Serve on injera."]),
    ("filipino", "kare-kare", "Kare-Kare", "Oxtail stew in peanut sauce with bagoong.", 0,
     ["stew", "oxtail", "classic"],
     ["oxtail", "peanut butter", "annatto", "eggplant", "bok choy", "bagoong"],
     ["Simmer oxtail until tender.", "Make peanut-annatto sauce.", "Add vegetables.", "Simmer until glossy.", "Serve with bagoong on side."]),
    ("filipino", "pancit", "Pancit Canton", "Stir-fried wheat noodles with soy and vegetables.", 0,
     ["noodles", "stir-fry", "party"],
     ["canton noodles", "soy sauce", "cabbage", "carrot", "shrimp", "pork"],
     ["Soak noodles.", "Stir-fry protein.", "Add vegetables.", "Toss noodles with soy.", "Garnish with calamansi."]),
    ("pakistani", "seekh-kebab", "Seekh Kebab", "Spiced minced lamb grilled on skewers.", 2,
     ["grill", "lamb", "classic"],
     ["ground lamb", "ginger", "garlic", "garam masala", "green chili", "coriander"],
     ["Mix lamb with spices.", "Mold onto skewers.", "Grill over charcoal.", "Turn until cooked through.", "Serve with naan and chutney."]),
    ("pakistani", "chapli-kebab", "Chapli Kebab", "Flat Peshawari minced meat patties with pomegranate.", 2,
     ["grill", "beef", "street food"],
     ["ground beef", "coriander seeds", "pomegranate seeds", "tomato", "green chili"],
     ["Mix beef with spices and seeds.", "Form flat patties.", "Pan-fry or grill.", "Serve with raita.", "Eat with naan."]),
    ("sri_lankan", "kottu-roti", "Kottu Roti", "Chopped godamba roti stir-fried on a griddle.", 2,
     ["stir-fry", "street food", "spicy"],
     ["godamba roti", "egg", "chicken", "carrot", "leeks", "curry spices"],
     ["Chop roti on hot griddle.", "Add vegetables and meat.", "Toss with spices.", "Crack egg into mix.", "Serve with gravy on side."]),
    ("sri_lankan", "fish-ambul-thiyal", "Fish Ambul Thiyal", "Sour black pepper fish curry from the south.", 2,
     ["curry", "fish", "classic"],
     ["tuna steaks", "goraka", "black pepper", "curry leaves", "coconut"],
     ["Toast pepper and goraka.", "Simmer fish in spiced coconut.", "Reduce until dry and sour.", "Rest flavors.", "Serve with rice."]),
    ("cambodian", "fish-amok", "Fish Amok", "Steamed fish custard in banana leaf cups.", 1,
     ["steamed", "fish", "classic"],
     ["white fish", "kroeung paste", "coconut milk", "egg", "banana leaves"],
     ["Blend kroeung with coconut.", "Fold in fish.", "Steam in leaf cups 20 min.", "Garnish with coconut cream.", "Serve warm."]),
    ("cambodian", "lok-lak", "Beef Lok Lak", "Stir-fried beef with lime-pepper dipping sauce.", 1,
     ["stir-fry", "beef", "classic"],
     ["beef strips", "oyster sauce", "tomato", "lettuce", "lime pepper dip"],
     ["Marinate and sear beef.", "Stir-fry with tomato.", "Make lime-pepper dip.", "Serve on lettuce cups.", "Eat with rice."]),
    ("brazilian", "feijoada", "Feijoada", "Black bean stew with smoked pork and sausage.", 0,
     ["stew", "pork", "classic"],
     ["black beans", "pork ribs", "linguiça", "bay leaves", "orange", "collard greens"],
     ["Soak beans overnight.", "Simmer with meats 3 hours.", "Skim and season.", "Serve with rice and greens.", "Garnish with orange."]),
    ("brazilian", "pao-de-queijo", "Pão de Queijo", "Chewy cheese bread made with tapioca flour.", 0,
     ["bread", "cheese", "snack"],
     ["tapioca flour", "cheese", "eggs", "milk", "oil", "salt"],
     ["Heat milk and oil.", "Mix into tapioca flour.", "Add cheese and eggs.", "Roll into balls.", "Bake until puffed."]),
    ("peruvian", "lomo-saltado", "Lomo Saltado", "Stir-fried beef with fries, soy, and ají amarillo.", 1,
     ["stir-fry", "beef", "fusion"],
     ["beef strips", "fries", "onion", "tomato", "soy sauce", "ají amarillo"],
     ["Sear beef over high heat.", "Add onion and tomato.", "Toss with soy and ají.", "Fold in crispy fries.", "Serve with rice."]),
    ("peruvian", "aji-de-gallina", "Aji de Gallina", "Creamy shredded chicken in walnut-aji sauce.", 1,
     ["chicken", "comfort", "classic"],
     ["shredded chicken", "ají amarillo", "walnuts", "evaporated milk", "bread", "parmesan"],
     ["Blend ají sauce with walnuts.", "Simmer with chicken.", "Thicken with bread.", "Serve over rice.", "Garnish with olives and egg."]),
    ("caribbean", "jerk-chicken", "Jerk Chicken", "Scotch bonnet-marinated grilled chicken.", 3,
     ["grill", "chicken", "classic"],
     ["chicken", "scotch bonnet", "allspice", "thyme", "scallion", "soy"],
     ["Blend jerk marinade.", "Marinate chicken overnight.", "Grill over pimento wood if possible.", "Char and rest.", "Serve with festival or rice."]),
    ("caribbean", "rice-and-peas", "Rice and Peas", "Coconut rice with kidney beans and thyme.", 0,
     ["rice", "side", "comfort"],
     ["jasmine rice", "kidney beans", "coconut milk", "thyme", "scallion", "garlic"],
     ["Sauté garlic and thyme.", "Add rice, beans, coconut milk.", "Simmer until fluffy.", "Rest covered.", "Fluff with scallion."]),
    ("taiwanese", "beef-noodle-soup", "Taiwanese Beef Noodle Soup", "Braised beef shank in spiced soy broth with noodles.", 2,
     ["noodles", "soup", "classic"],
     ["beef shank", "soy sauce", "star anise", "tomato", "wheat noodles", "bok choy"],
     ["Braise beef 2 hours in spiced soy.", "Cook noodles.", "Blanch greens.", "Assemble bowls.", "Top with pickled mustard."]),
    ("taiwanese", "lu-rou-fan", "Lu Rou Fan", "Braised minced pork over rice with pickled veg.", 0,
     ["rice", "pork", "comfort"],
     ["ground pork", "soy sauce", "rock sugar", "five-spice", "rice", "pickled cucumber"],
     ["Brown pork.", "Braise with soy and sugar.", "Reduce to thick sauce.", "Serve over rice.", "Add pickles on side."]),
    ("portuguese", "bacalhau-bras", "Bacalhau à Brás", "Shredded salt cod with eggs and matchstick potatoes.", 0,
     ["fish", "eggs", "classic"],
     ["salt cod", "potatoes", "eggs", "onion", "olives", "parsley"],
     ["Soak and shred cod.", "Fry potato matchsticks.", "Sauté onion and cod.", "Scramble in eggs.", "Garnish with olives."]),
    ("portuguese", "caldo-verde", "Caldo Verde", "Kale and potato soup with chouriço.", 0,
     ["soup", "comfort", "classic"],
     ["potatoes", "kale", "chouriço", "onion", "olive oil", "stock"],
     ["Simmer potatoes in stock.", "Blend partially.", "Add thinly sliced kale.", "Slice and fry chouriço.", "Serve with olive oil drizzle."]),
    ("british", "fish-and-chips", "Fish and Chips", "Beer-battered cod with thick-cut fries.", 0,
     ["fried", "fish", "classic"],
     ["cod fillets", "flour", "beer batter", "potatoes", "malt vinegar", "oil"],
     ["Cut and soak chips.", "Make light beer batter.", "Fry fish until crisp.", "Fry chips golden.", "Serve with vinegar."]),
    ("british", "shepherds-pie", "Shepherd's Pie", "Lamb mince topped with buttery mashed potato.", 0,
     ["baked", "lamb", "comfort"],
     ["ground lamb", "onion", "carrot", "peas", "mashed potato", "Worcestershire"],
     ["Brown lamb with vegetables.", "Simmer with Worcestershire.", "Top with mashed potato.", "Fork ridges on top.", "Bake until golden."]),
]


def _fmt_ingredients(raw: list[str]) -> str:
    return ",\n".join(f'            {{"name": "{item}"}}' for item in raw)


def _fmt_steps(steps: list[str]) -> str:
    escaped = [s.replace('"', '\\"') for s in steps]
    return ",\n".join(f'            "{s}"' for s in escaped)


def _esc(s: str) -> str:
    return s.replace('"', '\\"')


def main() -> None:
    out = Path(__file__).parent / "cuisine_expansion_v6_original.py"
    chunks = [
        '"""v6 original-cuisine depth — 31 cuisines × 2 extra recipes (62 total).',
        "",
        "Auto-generated by `generate_original_expansion.py`.",
        '"""',
        "",
        "from scripts.curated_data import RecipeSpec, _img",
        "",
        "ORIGINAL_EXPANSION_RECIPES: list[RecipeSpec] = [",
    ]
    for row in _DISHES:
        cuisine, slug, title, desc, spice, tags, ings, steps = row
        tag_str = ", ".join(f'"{t}"' for t in tags)
        chunks.append("    {")
        chunks.append(f'        "title": "{_esc(title)}",')
        chunks.append(f'        "description": "{_esc(desc)}",')
        chunks.append(f'        "cuisine": "{cuisine}", "language": "en", "spice_level": {spice},')
        chunks.append(f'        "prep": 15, "cook": 30, "servings": 4, "image": _img("{slug}"),')
        chunks.append(f'        "tags": [{tag_str}],')
        chunks.append('        "ingredients": [')
        chunks.append(_fmt_ingredients(ings))
        chunks.append("        ],")
        chunks.append('        "steps": [')
        chunks.append(_fmt_steps(steps))
        chunks.append("        ],")
        chunks.append("    },")
    chunks.append("]")
    chunks.append("")
    out.write_text("\n".join(chunks))
    print(f"Wrote {len(_DISHES)} recipes to {out}")


if __name__ == "__main__":
    main()
